### ISSUE TITLE
Conditions under which the "on end" callback is called

### ISSUE THREAD

**Issue by theliuk** [fastify/fastify-multipart#106]
I have noticed that, if the read stream representing the file being handled is not emptied, then the "on end" callback is not called.

In the main example we see how to use "pump" or "contact-stream" to empty the read stream inside the file handler; then the we answers the http request in the "on end" callback.
If someone forgets to empty the read stream and uses the "on end" callback to answer to http request, then no answer would be delivered.

If this is the expected behavior, in my opinion it's not well documented.
I'd be available to enhance the Readme with this consideration about this conditions for the "on end" callback to be called once the multipart request is properly handled.

Thank you for your attention

**Comment by mcollina** [comment]
That's the default behavior as it comes from https://github.com/mscdex/busboy, which we wrap. Would you mind to send a PR to update the README to clarify it?

**Comment by theliuk** [comment]
I’ll do.

**Comment by Eomm** [comment]
Merged in #107 

Thanks for improving the documentation 💪🏻
