### ISSUE TITLE
addToBody should have readable stream rather than buffer

### ISSUE THREAD

**Issue by amit12cool** [fastify/fastify-multipart#108]
I was integrating fastify multipart in my nestjs code and wanted to do the field validations in the multipart form data. 
I observed that the file data is put in body as data buffer rather than file stream.This willd efinitely impact the performance.
Can we have a file stream rather than buffer in body for file?

**Comment by mcollina** [comment]
In order to validate the body in validation phase of the lifecycle, the body needs to be fully parsed. 

Have you got any ideas on how to solve this?

**Comment by amit12cool** [comment]
Can we write the data to file system rather than buffer and provide the events on stream while the file is being written to file system.
Check this out
https://www.npmjs.com/package/formidable

**Comment by mcollina** [comment]
I’ll be happy to review a PR that adds similar functionity.

**Comment by amit12cool** [comment]
I will work on it.

**Comment by StarpTech** [comment]
You can use `onFile` handler to work with streams directly.
