### ISSUE TITLE
Async Await support

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify-multipart#109]
It would be great to have Async Await support in this module!
Would you like to work on it? Let us know below!

**Comment by ns23** [comment]
Hi can i work on it  ?

**Comment by surajrockzz** [comment]
Hii can I work on it?

**Comment by Swizz** [comment]
Hey ! 
Is there any progress on this ?

**Comment by StarpTech** [comment]
Async / await support is fully covered in the new implementation #140

**Comment by StarpTech** [comment]
Closed with #140
