### ISSUE TITLE
Is the "onEnd" callback mandatory? 

### ISSUE THREAD

**Issue by wolfejw86** [fastify/fastify-multipart#117]
I have a use-case where I want to essentially pull the stream out of these callbacks before I use it.  

```
return new Promise((resolve, reject) => {
  req.multipart(
    (field, filestream, originalFilename, encoding) => {
      resolve(filestream);
    },
    (err?: Error) => {
        // i don't care what happens here, i handle it elsewhere
    },
    {
      limits: {
        fileSize: TWO_MEGABYTES,
        fields: 0,
        files: 1,
      },
    },
  );
}
```

I'm trying to figure out if I have to worry about the onEnd call back as it just seems really verbose. I'd rather get access to the file that's being uploaded and resolve/pipe it somewhere else and handle the errors there.  As it looks now, it appears I can do that but also need to handle a seemingly arbitrary case around the onEnd callback.  Usually I notice the events happen in the following order, but I'm wondering if under certain circumstances that could change:

1. resolve / pipe the file somewhere else
2. initiate a pipe or a read on the file in it's new location (ie passed to another function somewhere else, for example trigger a stream upload to a blob storage)
3. the onEnd callback fires at somepoint.  

I'm basically trying to see is there anything that can happen in step 3 that I wouldn't be able to reasonably handle during step 2 in a different place? If so, it would be nice to figure out a clean way to make a promise implementation here.

**Comment by mcollina** [comment]
I think you have a really bad bug in your logic. Essentially you are creating a Promise that you might never resolve, very likely creating a memory leak :/.

Probably a full example would be needed, as it's totally unclear what you are trying to achieve.

**Comment by wolfejw86** [comment]
Yeah re-reading the above it does sound convoluted.  I'll try to put together a full example I can share.  Here is hopefully a simpler summary that may at least give insight into what I'm trying to deal with:

- upload file to fastify endpoint
- pipe upload stream to a blob storage
- the `onEnd` callback gets fired BEFORE the resolution of the blob storage upload (which makes sense bc it would need to finish "reading" the stream before finishing the upload.)

What I'm looking for is a preferred way to handle waiting for an immediate response from the file upload before sending an http response, but the fact that it can fail in the `onEnd` callback AND throw an error in the blob storage upload (happening inside of the file handler callback) makes it difficult to "catch" everything in one place.  It's also very possible I'm overthinking it or missing a key part of how this flow typically works.

**Comment by mcollina** [comment]
I think you might be complicating your life by wrapping it inside a Promise.

**Comment by wolfejw86** [comment]
Okay, sorry for the convoluted example, but it was the best I could come up with.  Again I may just be overthinking it, but it seems like there's a situation where the stream onEnd could have an error and then an error would also be triggered inside my upload function.

```
const Fastify = require("fastify");
const fastifyMultipart = require("fastify-multipart");
const fp = require("fastify-plugin");

const TWO_MEGABYTES = 1024 * 1024 * 2;

const fastify = Fastify();

fastify.register(fp(fastifyMultipart));

/**
 * function finishes AFTER the onEnd handler
 */
const fakes3StreamUpload = (stream, throwError = false) => {
  return new Promise((resolve, reject) => {
    if (throwError) {
      stream.destroy();
    } else {
      stream.resume();
    }

    setTimeout(() => {
      if (throwError) {
        return reject("You're gonna have a bad time.");
      }

      resolve("Yay.");
    }, 3000);
  });
};

fastify.route({
  method: "PUT",
  url: "/file-upload",
  handler: function(request, reply) {
    function handler(field, file, filename, encoding) {
      // watch limit and end stream if reached, passes to error handler just fine
      // file.on("limit", function() {
      //   file.destroy();
      // });

      // upload to s3 - reads stream all the way through, triggering on end but upload is not finished
      // need a good way to wait for upload to finish
      // fakes3StreamUpload(file, true) // uncomment to see error case
      fakes3StreamUpload(file)
        .then(() => {
          // need to wait for this to finish before sending http reply
          reply.send({ success: true, uploaded: true });
        })
        .catch(err => {
          // need to handle this error, seems like sometimes i will need to reply here, while sometimes needing to reply in the onEnd
          reply.code(500).send({ err });
        });
    }

    function onEnd(err) {
      // fires before asynchronous action on file stream is finished :(
      // if error happens here but error also gets thrown in s3 upload example, will it always hit this
      // handler callback first? would it be best to have a "conditional here saying, if error here then go ahead and reply"
      // and if i've already replied, just ignore the error in the upload (still catch it, just don't do anything with it)
      if (err) {
        reply.code(500).send({ err });
      }
    }
    request.multipart(handler, onEnd, {
      limits: {
        fileSize: TWO_MEGABYTES,
        fields: 0,
        files: 1
      }
    });
  }
});

fastify.listen(8080, () => {
  console.log("listening");
});

```

**Comment by Eomm** [comment]
I think we should be more clear:
- the `handler` is called for every multipart field, so if you send 2 files, it will be called twice
- the `onEnd` function will be called when all the request stream has been consumed, it doesn't refer to a single file

I think it is wrong sending a `replay.send()` in the handler, but it should put in the `onEnd` function refactoring your code.

> "conditional here saying, if error here then go ahead and reply"
    
Anyway, if you write:

```
replay.send('hello')
replay.send('world')
```
only the first sentence will be executed and the second one will log a warning

**Comment by wolfejw86** [comment]
Thank you for chiming in.  I did understand the part about multiple files and onEnd not happening until all of them had been processed. 

My area of concern centers around the fact that while _the last file stream has finished processing_ the asynchronous action I passed that filestream to in the handler function _is not finished_.  It is the latter that I care about waiting for before sending an API response.  This means that the `onEnd` callback _has been called_ but asynchronous code is still waiting/running inside of the handler block.  

I can't help but think I'm missing obvious here, but so far I'm coming up short. Perhaps it's a design flaw.  In a perfect world I would "fire and forget" the passing of the file stream in the handler, but that is not an option at this point in time.

**Comment by Eomm** [comment]
Oh, I understand.

Who is the streamwriter? Does it implement all the [stream lifecycle](https://nodejs.org/es/docs/guides/backpressuring-in-streams/#lifecycle-of-pipe)?

**Comment by mcollina** [comment]
I would recommend you _not to mix promises and streams_ in that handler. 

This is solvable by using https://nodejs.org/api/stream.html#stream_stream_finished_stream_options_callback or https://nodejs.org/api/stream.html#stream_stream_pipeline_source_transforms_destination_callback on the uploading stream.

Your goal is to send your response inside `onEnd` or when the uploading stream has finished uploading. Both these conditions can happen in any order. Moreover, you can have more than one file so you'll need to track them all.

The idea is keep a bit of state and send your response only when all uploading streams are finished and `onEnd` has been called.

**Comment by wolfejw86** [comment]
Okay, after doing some further reading, I think there's a conflict in the approach of some of the other libs I'm using vs the generalist approach that busboy uses.  It does handle multiple files, but I've limited it to 1 and according to the docs, any additional will be "safely discarded".  It also uses callback apis whereas the other tools I'm using are only promise based.

I can't rightly use the stream lifecycle events as suggested because the blob storage upload library is only promise based, as is the `file-type` package where I validate if it's specifically a .PNG file or not.  So I'm stuck with a mix of callback vs promise based APIs already anyways, and I think the best course of action is mostly what I'm already doing which is basically as @mcollina suggested which is to keep some state and manage all the edges.

I feel like this code is really ugly, but may do the trick:
```
class MultipartStreamWatcher extends EventEmitter {
  constructor() {
    super();

    this.error = this.error.bind(this);
    this.success = this.success.bind(this);
  }
  finished() {
    return new Promise((resolve, reject) => {
      this.once("finished", (err, result) => {
        if (err) {
          return reject(err);
        }

        resolve(result);
      });
    });
  }
  error(err) {
    this.emit("finished", err);
  }
  success(result) {
    this.emit("finished", null, result);
  }
}

fastify.route({
  method: "PUT",
  url: "/file-upload",
  handler: async (request, reply) => {
    const streamWatcher = new MultipartStreamWatcher();
    let atLeastOneUpload = false;

    function handler(field, file, filename, encoding) {
      atLeastOneUpload = true;
      file.on("limit", function() {
        streamWatcher.error(new Error("Filesize too large."));
        file.destroy();
      });

      fakes3StreamUpload(file)
        .then(streamWatcher.success)
        .catch(streamWatcher.error);
    }

    function onEnd(err) {
      if (err) {
        return streamWatcher.error(err);
      } else if (!atLeastOneUpload) {
        return streamWatcher.error(new Error("Must upload at least one file."));
      }

      // all other cases will be handled in the upload promise resolution
    }
    request.multipart(handler, onEnd, {
      limits: {
        fileSize: TWO_MEGABYTES,
        fields: 0,
        files: 1
      }
    });

    const uploadResult = await streamWatcher.finished(); // or just throw to error handler

    // save reference to db / do other stuff

    // send payload response
    return {
      success: true
    };
  }
});
```

Any helpful hints are suggested :)  Thanks for all the responses so far.

**Comment by mcollina** [comment]
That will work.
