### ISSUE TITLE
Fields arrays not working

### ISSUE THREAD

**Issue by morigs** [fastify/fastify-multipart#120]
## 🐛 Bug Report

Currently, it's impossible to accept multipart requests with array fields. It's a common pattern to duplicate field to pass an array ([example](https://stackoverflow.com/questions/10002821/how-do-i-post-an-array-with-multipart-form-data-encoding)). Owner of busboy [recommends](https://github.com/mscdex/busboy/issues/159#issuecomment-354678039) to check duplicates of keys and create arrays. But [this line](https://github.com/fastify/fastify-multipart/blob/d298f193dc4e0d0a446fae70789ceeafc05e3211/index.js#L54) is always overriding previous value of the field.

## To Reproduce

```ts
const instance: fastify.FastifyInstance<Server, IncomingMessage, ServerResponse> = fastify();
instance.register(fastifyMultipart, { addToBody: true });
instance.route({
  method: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'HEAD', 'OPTIONS'],
  url: '/echo',
  handler: (request, reply) => {
    reply.code(200).send({
      body: request.body,
      headers: request.headers,
      path: request.req.url,
      method: request.req.method,
    });
  },
});

// then request using any client with the following options
{
    url: `http://${host}/echo`,
    method: 'POST',
    multipart: { someField: ['123', '321'] },
  }
```

## Expected behavior

Expected response body:

```js
{
   headers: {...},
   path: '/echo',
   method: 'post',
   body: {
     someField: ['123', '321'],
   },
}
```

Actual:

```js
{
   headers: {...},
   path: '/echo',
   method: 'post',
   body: {
     someField: '321',
   },
}
```

## Your Environment

- *node version*: 12.16.2
- *fastify version*: 2.14.0
- *os*: Windows
- *fastify-multipart version*: 1.0.5

## Suggestion

Maybe change [this line](https://github.com/fastify/fastify-multipart/blob/d298f193dc4e0d0a446fae70789ceeafc05e3211/index.js#L54) to something like this:

```js
if (body[key] === undefined) {
  body[key] = value
} else if (Array.isArray(body[key])) {
  body[key].push(value)
} else {
  body[key] = [body[key], value];
}
```

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by morigs** [comment]
Here we go. Please double-check my PR, I'm not sure that I took into account all possible cases

**Comment by quydox** [comment]
Hello, there is one more error

# POST
ids[]=10
ids[]=11

expected 
ids: [10, 11]

currently
ids[]: [10, 11]

Can you remove '[]' on body key?

I try to remove '[]' on your installed module, it works
```
      name = name.replace('[]', '')
      if (body[name] === undefined) {
        body[name] = value
      } else if (Array.isArray(body[name])) {
        body[name].push(value)
      } else {
        body[name] = [body[name], value]
      }
```

Thanks
