### ISSUE TITLE
Is there proper example on how to cancel upload?

### ISSUE THREAD

**Issue by yaneony** [fastify/fastify-multipart#131]
Just wondering if there is some proper example on how to cancel upload on some of event, like "partsLimit", "filesLimit", "fieldsLimit", "limit"? Had anyone success on checking and canceling them?!

**Comment by mcollina** [comment]
Possibly with `req.raw.destroy()`? I've actually never tried.

**Comment by yaneony** [comment]
For an example, i would allow users to create some kind of "content", forum thread, or anything like that... User will be able to upload up to 3 files, 10mb each max. So, someone will upload 10 files instead of 3 and some of those files will be larger than 10mb... There should be some possibility to cancel uploads if any of limits meant above ("partsLimit", "filesLimit", "fieldsLimit", "limit") occurred...

**Comment by mcollina** [comment]
I think calling the callback with an error or `reply.send(new Error(‘too big’))` should do the trick.

**Comment by yaneony** [comment]
`req.raw.destroy()` partially do the trick if you put in into 'limit' event, but, the problem is that application still trying to do something and you don't get any reply from your web/api until some timeout... I'm just looking for any good way to stop busboy processing any of "fields" if any of file/field limits has hit.

**Comment by yaneony** [comment]
Answering my own question: 

To prevent firing "finish" event on any processing after you hit "limit", you will have to "unpipe" the Busboy instance from your request.

That code do the trick:
```
    file.on('limit', () => {
      console.log('File size limit reached');
      req.raw.unpipe(mp);
      res.send(new Error('File size limit reached'));
    });
```

**Comment by mcollina** [comment]
That's awesome! It would be handy to add an `mp.abort()` method that does the above.

**Comment by yaneony** [comment]
So, i've digged around and it looks like that's the only possible variant to cancel upload while hitting the limit. Otherwise, if you don't do that, your app will wait until full file size is consumed.

Following, try to set limit to 1mb and try to upload 700mb file. You will see that it will take as long as it would take to upload full 700mb file and will not break after 1mb is done.

To note is, that it will not work with `addToBody: true` together, since there are no `req` and `res` objects in there.

**Comment by mcollina** [comment]
A PR for this would be amazing!

**Comment by mcollina** [comment]
That seems about how I would handle it! 
One of the things we can do is to add handling of those events in `addToBody`.

**Comment by yaneony** [comment]
One small improvement, you have to add header to close the connection or your browser will hang until it times out. 
Here the code: 

`return res.code(400).header('Connection', 'close').send(err);`

So far, that's working very well.

**Comment by yaneony** [comment]
I think that's a proper and good example to upload, check and to do what you want with files you upload. Now i will close it, reopen if required.

**Comment by mcollina** [comment]
Please send a PR!

**Comment by 58bits** [comment]
Thanks for the example @yaneony. We came across this just now. Per request `addToBody ` with the extra mp event handlers would be very nice.

**Comment by 58bits** [comment]
We created a multipart handler file - based on @yaneony example above. https://gist.github.com/58bits/44d6463f3df6d652601c74e63736b693 - in the gist we've begun to implement some of our own configuration, and error handling, so this is not completely generalized. Our schemas for body / field validation are also imported separately.

With this we can now create request-specific handlers like...

```
'use strict'

const schemas = require('./schemas')
const { Multipart } = require('../../../lib/multipart')

 /**
   * Create Template
   */
  app.route({
    method: 'POST',
    url: '/',
    onRequest: app.authorize('email_template:create'),
    schema: schemas.create,
    preValidation: Multipart,
    handler: async (request, reply) => {
      try {
        let emailTemplate = await createEmailTemplate(context(app, request), request.body)
        reply.code(200).send({ data: normalize(emailTemplate) })
      } catch (error) {
        reply.header('Connection', 'close').send(error)
      }
    },
  })
```
Again... thanks for showing us the way @yaneony

**Comment by BlackGlory** [comment]
In the current version, both `req.raw.destroy()` and `Connection: close` cannot abort the connection, any updates?
