### ISSUE TITLE
What is the purpose on using "req.multipart(handler, onEnd)"?

### ISSUE THREAD

**Issue by yaneony** [fastify/fastify-multipart#132]
What is the purpose on using "req.multipart(handler, onEnd)", i mean the "handler" and "onEnd", when that is an instance of busboy and busboy event could be used? I see there only an "short" advantage if you're using files only, and if you process another text/form fields, you will have to use
```
  mp.on('field', function (key, value) {
    console.log('form-data', key, value)
  })
```
anyway in that case. So, what's the purpose on "re-defining" existing events?!

**Comment by yaneony** [comment]
So, the following code

```
fastify.post('/', function (req, reply) {
  if (!req.isMultipart()) {
    reply.code(400).send(new Error('Request is not multipart'))
    return
  }

  const mp = req.multipart(handler, onEnd)

  mp.on('field', function (key, value) {
    console.log('form-data', key, value)
  })

  function onEnd(err) {
    console.log('upload completed')
    reply.code(200).send()
  }

  function handler (field, file, filename, encoding, mimetype) {
    pump(file, fs.createWriteStream('a-destination'))
  }
})
```

could be easily repalced with

```
fastify.post('/', function (req, reply) {
  if (!req.isMultipart()) {
    reply.code(400).send(new Error('Request is not multipart'))
    return
  }

  const mp = req.multipart(() => {}, () => {})

  mp.on('field', function (key, value) {
    console.log('form-data', key, value)
  })

  mp.on('file', function (fieldname, file, filename, encoding, mimetype) {   
    pump(file, fs.createWriteStream('a-destination'))
  });

  mp.on('finish', function () {
    console.log('upload completed')
    reply.code(200).send()
  });

})
```

**Comment by mcollina** [comment]
The `onEnd` function is called _when all files are processed_, while `'finish'` is emitted when all the files have been received. There is a subtle difference in handling errors.
The `handler` is called after `onEnd` is hooked up correctly, however it's not really needed and something we could remove.

**Comment by yaneony** [comment]
What do you mean by "when all files are processed"? What is "processing" in that case?

**Comment by mcollina** [comment]
Essentially when all streams have been fully consumed.

**Comment by yaneony** [comment]
Thanks for explaining!
