### ISSUE TITLE
Improve developer experience

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify-multipart#139]
## 🚀 Feature Proposal

Today, I needed to develop a simple image upload service in fastify and it felt unsatisfying.

## Motivation

Handling multipart form data should be dead simple and intuitive in fastify.

-  Support `async / await` (async stream iterators)
- Zero boilerplate, provide fastify-hooks to do all this stuff with good defaults (like in expressjs/multer `upload.single("uploaded_file")` )
- Delegate busboy failures to fastify (like in expressjs https://github.com/expressjs/multer/blob/6b5fff5feaf740f249b1b2858e5d06009cbd245c/lib/make-middleware.js#L167-L170)

## Example

In https://eggjs.org/en/basics/controller.html#acquiring-the-submitted-files you can easily switch different modes without dealing with too much boilerplate.

```js
// Single file in disk storage mode
app.post("/images", async (req, res) => {
  req.file.filename
  req.file.mimetype
  // async / await
})

// Multiple files in disk storage mode
app.post("/images", async (req, res) => {
  req.files
})

// Single file in stream mode
app.post("/images", async (req, res) => {
   const stream = await ctx.getFileStream();
})

// Multiple files in stream mode
app.post("/images", async (req, res) => {
 const parts = ctx.multipart();
    let part;
    // parts() return a promise
    while ((part = await parts()) != null) {}
})
```

in fastify you need for the same behaviour a lot of boilerplate and you are responsible to handle all cases manually.

```js
fastify.register(require('fastify-multipart'))

fastify.post('/upload', function (req, reply) {
  const mp = req.multipart(handler, function (err) {
    console.log('###2');
    if (err) {
      reply.send(err)
      return
    }
    console.log('upload completed', process.memoryUsage().rss)
    reply.code(200).send()
  })

  mp.on('field', function (key, value) {
    console.log('form-data', key, value)
  })

  function handler (field, file, filename, encoding, mimetype) {
    pump(file, fs.createWriteStream('a-destination'), (err) => {
      console.log('###1');
    })
  }
})
```

Logs:

```
server listening on 3000
###2
upload completed 31477760
###1
```

Additional problems for the users:
- `onEnd` is fired before the file was written.

**Comment by fox1t** [comment]
What about https://www.npmjs.com/package/fastify-multer for the same old multer DX?

**Comment by StarpTech** [comment]
@fox1t great I didn't know it.

**Comment by StarpTech** [comment]
Since this is the core package we should try to improve this package or switch to fastify-multer entirely.

**Comment by fox1t** [comment]
We might also move fastify-multer under fastify organization here on GitHub.

**Comment by Eomm** [comment]
I added the `addToBody` options for this purpose, but I agree, it could be improved in performance and docs

```
  fastify.register(multipart, { addToBody: true })

  fastify.post('/', function (req, reply) {
    t.equal(req.body.myField, 'hello')
    t.type(req.body.myFile[0].data, Buffer)
    reply.send('ok')
  })
```

**Comment by StarpTech** [comment]
@Eomm nice. Performance shouldn't be a priority in that iteration. I'd like to have a very simple module that uploads files default to disk with additional options for streams and memory. fastify-multer looks very promising. @fox1t do you think adding a stream storage mode would be a good enhancement?

**Comment by StarpTech** [comment]
I really like the api in https://eggjs.org/en/basics/controller.html#acquiring-the-submitted-files

**Comment by fox1t** [comment]
@aichholzer i think that this is one of the killer features. Sometime ago I was working on this https://www.npmjs.com/package/storagecoach but actually I never finished it nor decided the API I wanted to expose. The idea is to have only one interface that exposes only streams and then uses drivers internally to upload to disk/azure blob storage, s3, or GCP.

**Comment by mcollina** [comment]
+1, improving the multipart story of Fastify would benefit a lot the comunity!

**Comment by jsumners** [comment]
🤔 The current implementation offers flexibility in testing. I am able to hook into the events to inspect that things are handled correctly.

**Comment by StarpTech** [comment]
I prepared a first https://github.com/fastify/fastify-multipart/pull/140 to overhaul the current interface.

**Comment by StarpTech** [comment]
Implemented and merged.
