### ISSUE TITLE
fastify-multipart v 3.0 not able to access key/value pairs with upload binary file

### ISSUE THREAD

**Issue by outbackStack** [fastify/fastify-multipart#146]
## 🐛 Bug Report
Thanks for improving this plugin to make it easier for files upload.
I've switched over to v3.0 and tried out the new API but it's not letting me access the fields data like the legacy version

## To Reproduce

Client form
```js
    const formData = new FormData();
    formData.append("avatar", file, file.name); // <input type="file" />
    formData.append("testData", JSON.stringify({ name: "Foo" })); 

    fetch("/", {
      method: "POST",
      body: formData
    })
```

Server
```js
    fastify.post('/', async function (req, reply) {
        const data = await req.file()

        data.file // stream
        data.fields // other parsed parts
        data.fieldname
        data.filename
        data.encoding
        data.mimetype

        console.log(JSON.parse(data.fields))

        await pump(data.file, fs.createWriteStream(data.filename))

        reply.send()
    })
```

## Expected behavior

print out { name: 'Foo' }

in the legacy version, i could access it under this:
```js
  mp.on('field', function (key, value) {
    console.log(JSON.parse(value))
  })
```

## Your Environment

- *node version*: 12
- *fastify version*: >=3.0.0
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
cc @StarpTech

**Comment by StarpTech** [comment]
We can't parse out of sync because files must be handled first. In order to archive your result, you have to reorder your form

```
	formData.append("testData", JSON.stringify({ name: "Foo" }));
    formData.append("avatar", file, file.name); // <input type="file" /> 
```

**Comment by StarpTech** [comment]
or you use `multipartIterator `to iterate over field and files.

**Comment by kibertoad** [comment]
@StarpTech It's an easy mistake to make, though. Can we improve error message in this case, offering suggestions to check for this exact case?

**Comment by StarpTech** [comment]
Not sure, how we can improve the error message if don't produce one. Would you like to improve the docs? smt like:
 
> Due to the nature of busboy files must be consumed before another field/file can be picked. This is important, if you have to rely on different values. Ensure that the order of your multipart form reflects that.`

Related issue: https://github.com/mscdex/busboy/issues/43, https://github.com/mscdex/busboy/issues/97

**Comment by StarpTech** [comment]
Just for completeness: You can use `const files = await req.saveRequestFiles()` to pump all files to disk and all fields are available.

**Comment by RareLambChops** [comment]
thanks @StarpTech , it works if they are in the correct order and ```js multipartIterator() ``` works too but that doesn't need to be in order. 

Maybe we can add in the note for the first sample to flag this issue if they encounter it with this API?

```js
  data.file // stream
  data.fieldname
  data.filename
  data.encoding
  data.mimetype
  data.fields // form fields need to be in the correct order from the client side or
  // use multipartIterator() to iterate over field and files if the order is not possible.

```

**Comment by RareLambChops** [comment]
btw @StarpTech, the new API is really easy to use so thanks again for that! 😊

**Comment by StarpTech** [comment]
@RareLambChops thanks and great to hear. Would you like to create PR?

**Comment by StarpTech** [comment]
Closing the issue because it's the inherited behavior of busboy.
