### ISSUE TITLE
Throws request is not multipart when it actually is

### ISSUE THREAD

**Issue by kaleidawave** [fastify/fastify-multipart#148]
## 🐛 Bug Report

Throws this on valid request:
```json
{
  "statusCode": 406,
  "code": "FST_INVALID_MULTIPART_CONTENT_TYPE",
  "error": "Not Acceptable",
  "message": "the request is not multipart"
}
```

## To Reproduce

`server.js`:
```js
const fastify = require("fastify");

const app = fastify()

app.register(require("fastify-multipart"));

app.get("/abc", async (req, res) => {
    console.log(await req.file());
    res.send("");
});

app.listen(3000);
```

The raw request coming in:
```
> GET /abc HTTP/1.1
> Host: localhost:3000
> User-Agent: insomnia/2020.3.3
> Sec-Fetch-Dest: empty
> DNT: 1
> Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY
> Accept: */*
> Content-Length: 115

| --X-INSOMNIA-BOUNDARY
| Content-Disposition: form-data; name="email"
| example@gmail.com
| --X-INSOMNIA-BOUNDARY--
```

## Expected behavior

Not to throw, and for `(await req.file()).fields["email"]` to have string content

## Your Environment

- *node version*: v12.14.1
- *fastify version*: 3.1.1
- *fastify-multipart version*: 3.0.0

**Comment by StarpTech** [comment]
I see two issues:

- You use `GET`
- Expect a file although you send a string.

**Comment by CMCDragonkai** [comment]
I've done something that looks like this:

```
    fastify.post('/upload', async (request, reply) => {
      const fileData = await request.file();
      await reply.send({ got: 'it' });
    });
```

And then I use httpie:

```
http -f POST http://localhost:33067/upload x=y file@./README.md --verbose
```

This produces a:

```
POST /upload HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 9294
Content-Type: multipart/form-data; boundary=5af381832d674fc39712598dbda9845a
Host: localhost:33067
User-Agent: HTTPie/3.2.2

--5af381832d674fc39712598dbda9845a
Content-Disposition: form-data; name="x"

y
--5af381832d674fc39712598dbda9845a
Content-Disposition: form-data; name="file"; filename="README.md"
Content-Type: text/markdown

...
```

But then I keep getting the same error as the OP.

**Comment by CMCDragonkai** [comment]
There's no indication as to why this is happening... how can we debug why that error appears and trace it backwards.

I looked into it, and it seems `this[kMultipart]` is still `false`.

I also use:

```
    fastifyServer.removeAllContentTypeParsers();
```

Later in an encapsulated plugin. Would that affect this?

**Comment by amydevs** [comment]
there's no way to encapsulate contentTypeParsers within specific routes or plugins, so `removeAllContentTypeParsers` will remove all `ContentTypeParsers` assigned before it
