### ISSUE TITLE
Fastify request file call never returns

### ISSUE THREAD

**Issue by GogaRUFI** [fastify/fastify-multipart#157]
## 🐛 Bug Report

If multipart form data fields aren't appended in a specific order, the `request.file()` never returns.

## To Reproduce

CLIENT:

```js
const formData = new FormData();
const fileField = document.querySelector('input[type="file"]');

formData.append('username', 'abc');
formData.append('avatar', fileField.files[0]);
// NOTE: This is the line that causes the unexpected behavior  - adding a text filed after adding a file.
formData.append('email', 'abc@example.com');

fetch('https://example.com/", {
  method: 'POST',
  body: formData
})
```

SERVER:

```js
const fastify = require('fastify')()
const fs = require('fs')
const util = require('util')
const path = require('path')
const { pipeline } = require('stream')
const pump = util.promisify(pipeline)

fastify.register(require('fastify-multipart'))

fastify.post('/', async function (req, reply) {

  // The call never returns:
  const data = await req.file()

  await pump(data.file, fs.createWriteStream(data.filename))
  reply.send()
})
```

## Expected behavior

The file call bellow returns either a failed promise with a meaningful error message or resolves successfully.

```js
...
  // The call returns a promise
  const data = await req.file()
...
```

## Your Environment

- *node version*: 12.16.3
- *fastify version*: 3.4.1
- *os*: Mac
- *fastify-multipart*: 3.2.0
- *Firefox*: 80.0.1

**Comment by StarpTech** [comment]
I can't reproduce it. We have a test with the same semantic. @GogaRUFI could you try to add a failing test?

**Comment by nurdism** [comment]
I am running into similar issues with the async iterator, I am running this code:
```js
for await (const part of req.parts()) {
  console.log(part)
  req.body = part.fields
  if (part.file) {
    const buff = await part.toBuffer()
    console.log('toBuffer', buff.toString())
  }
  console.log('done')
}

console.log('preValidation')
```
if I have a file in the multipart request the request will hang and never complete the promise

did some digging and found that https://github.com/fastify/fastify-multipart/blob/master/index.js#L344 get called at the very beginning of the request, it then calls `cleanup()` witch does not resolve the promise, changing it to the `onEnd` func seems to resolve this issue

**Comment by StarpTech** [comment]
@nurdism could you please provide a full example? A failing unit test would be great.

**Comment by StarpTech** [comment]
I tried this and it works without any error.

```js
fastify.post('/upload/stream/single-buf', async function (req, reply) {
  for await (const part of req.parts()) {
    if (part.file) {
      const buff = await part.toBuffer()
      console.log(part)
    }
  }
  reply.send()
})
```
