### ISSUE TITLE
Inconsistent behavior when handling file limits

### ISSUE THREAD

**Issue by bmo-at** [fastify/fastify-multipart#160]
## 🐛 Bug Report

The limits you can give to fastify-multipart are handeled in an inconsistent way.

If, for example, you give it a limit for the number of files it will automatically end the request with a 413 or alternatively I can catch the error that saveRequestFiles() throws and create my own response on top of that.

However, if I give it a limit for the file size it will not do the same.

In the docs it says to catch the errors associated with file limits. But a file that is too large never throws an error up to the application level, instead it is logged twice, once as a warning and then again as an error down in the saveRequestFiles() method.

It never bubbles up and is not catchable for me.

The problem here is that I can then never properly end the request and the client is just stuck.

## To Reproduce

```js
const server = require('fastify')({ logger: true });

server.register(require('fastify-multipart'), { limits: { files: 1, fileSize: 1 * 1000 * 1000 } });

server.route({
    method: "POST",
    url: '/upload',
    handler: async (req, res) => {

        let files ;

        try {
            files = await req.saveRequestFiles();
        } catch (error) {
            req.log.error(error);
            res.status(500).send('error');
        }
        if (!res.sent) { res.send(`done. ${files.length} files received`); }
    }
});

server.listen(8080, (error) => {
    if (error) {
        server.log.error(error);
        process.exit(1);
    }
})
```

## Expected behavior

This server should accept requests of up to one file per request with a maximum size of 1 megabyte. 

saveRequestFiles() should throw an error whenever it runs into a file limit which can then be handled by the developer.

Alternatively, if the developer does not handle the error, it should end the request with a 413 code like it already does for the limit for number of files.

## Your Environment

- *node version*: 12
- *fastify:* 3.4.1
- *fastify-multipart*: 3.2.0
- *os*: Debian 10 on WSL2

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by bmo-at** [comment]
I'll be honest, I'd love to. But I am only a college student and while my employer does permit and even encourage OSS contributions at work, I am currently in quite a time crunch to get my project done today before I head into two weeks of vacation to prepare for an exam.
After that? Sure, I'd love to contribute but I assume by that time you'll want this problem dealt with.

**Comment by StarpTech** [comment]
Indeed `saveRequestFiles` try to consume as many files as possible without throwing. We could handle in two ways:

1. Rethrow on errors https://github.com/fastify/fastify-multipart/blob/master/index.js#L485
2. Expose the latest file error on a request decorator so you can check for errors without aborting the whole upload process.

**Comment by mcollina** [comment]
I think rethrowing on error is the best path forward.
