### ISSUE TITLE
request stale when using with fastify-auth

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify-multipart#188]
## To Reproduce

```js
// fastify-multipart setting
fastify.register(FastifyMultipart, {
  limits: {
    fieldNameSize: 100, // Max field name size in bytes
    fieldSize: 1000000, // Max field value size in bytes
    fields: 10, // Max number of non-file fields
    fileSize: 1000000, // For multipart forms, the max file size
    files: 10, // Max number of file fields
    headerPairs: 2000 // Max number of header key=>value pairs
  }
})

// fastify-auth setting
fastify.register(FastiftJwt, {
  secret: 'lapcom',
  verify: {
    ignoreExpiration: false
  },
  sign: {
    expiresIn: '30 minutes'
  }
})

// verification code
fastify.decorate('verifyJWTandMongoDB', async function (request: any) {
  const { authorization } = request.headers;
  if (!authorization || !String(authorization).startsWith('Bearer ')) {
    throw new Error('Invalid Token');
  }
  const decoded = fastify.jwt.verify(authorization.replace('Bearer ', ''));
  if (!decoded) {
    throw new Error('Invalid Token');
  }
});

// route
fastify.post(
  '/import',
  {
    preHandler: fastify.auth([fastify.verifyJWTandMongoDB])
  },
  async function (request, _reply) {
    const parts = await request.parts();
    const base = {};
    let batch = [];
    for await (const part of parts) {
      if (part.file) {
        const result = await csvtojson({
          noheader: true,
          headers: [ ... ]
        })
          .fromStream(part.file)
          .subscribe((formatted) => Promise.resolve(formatted));
          batch = batch.concat(result);
      } else {
        const field = part
        base[field.fieldname] = field.value;
      }
    }

    const results = await Promise.all(
      batch.map(async function (each) {
        return ...
      })
    );

    const result = results.filter(function (result) {
      return !(result instanceof Error);
    });

    return {
      success: true,
      result,
      total: batch.length,
      failed: batch.length - result.length
    };
  }
);
```

## Expected behavior

Run smoothly when I apply the ```fastify.auth([fastify.verifyJWTandMongoDB])``` preHandler

## Your Environment

- *node version*: 14
- *fastify version*: >=3.0.0
- *os*: Windows
- *any other relevant information*

**Comment by climba03003** [comment]
no idea if it is related to #185

**Comment by Eomm** [comment]
I cant replicate with 

```
const fastify = require('fastify')({ logger: true })

fastify.register(require('./index'), {
  limits: {
    fieldNameSize: 100, // Max field name size in bytes
    fieldSize: 1000000, // Max field value size in bytes
    fields: 10, // Max number of non-file fields
    fileSize: 1000000, // For multipart forms, the max file size
    files: 10, // Max number of file fields
    headerPairs: 2000 // Max number of header key=>value pairs
  }
})

fastify.register(require('fastify-auth'))
  .after(() => {
    fastify.decorate('verifyJWTandMongoDB', async function (request) {
      const { authorization } = request.headers
      if (!authorization || !String(authorization).startsWith('Bearer ')) {
        throw new Error('Invalid Token')
      }

      if (authorization !== 'Bearer test') {
        throw new Error('Invalid Token')
      }
    })

    // route
    fastify.post('/import', {
      preHandler: fastify.auth([fastify.verifyJWTandMongoDB])
    },
    async function (request, _reply) {
      const parts = await request.parts()
      const base = {}
      for await (const part of parts) {
        if (part.file) {
          console.log(part.file)
          part.file.pipe(process.stdout)
        } else {
          const field = part
          base[field.fieldname] = field.value
        }
      }
      return {
        success: true
      }
    })
  })
fastify.listen(8080)
```

I think the issue is here:

```
const result = await csvtojson({
          noheader: true,
          headers: [ ... ]
        })
          .fromStream(part.file)
          .subscribe((formatted) => Promise.resolve(formatted));
```

Because the `part.file` must be consumed (`part.file.pipe(process.stdout)`) otherwise the response will never be sent

**Comment by climba03003** [comment]
I will check if it is the issue with ```csvtojson```.
The main reason I though it is the problem between ```fastify-multipart``` and ```fastify-auth``` is that when I do not put the ```preHandler``` it work properly. The response didnt sent only when there are ```preHandler```.

**Comment by Eomm** [comment]
Oh, clear: it seems harder to debug then.

I would focus on the `verifyJWTandMongoDB` then tho

**Comment by climba03003** [comment]
> 
> 
> Oh, clear: it seems harder to debug then.
> 
> I would focus on the `verifyJWTandMongoDB` then tho

I have tried to remove ```csvtojson```, but the result is the same.
It seems that when I add the preHandler, the file stream will never be closed.
So, the route is stuck inside the for loop.

**Comment by climba03003** [comment]
I think I miss the important piece. It is the problem of ```verifyJWTandMongoDB```.

```javascript
fastify.decorate('verifyJWTandMongoDB', async function (request: any) {
  const { authorization } = request.headers;
  if (!authorization || !String(authorization).startsWith('Bearer ')) {
    throw new Error('Invalid Token');
  }
  const decoded = fastify.jwt.verify(authorization.replace('Bearer ', ''));
  if (!decoded) {
    throw new Error('Invalid Token');
  }
  const item = await fastify.mongo.db.collection('jwt').findOne({ id: decoded.id  });  // this line cause the problem
  if (!item) {
    throw new Error('Invalid Token');
  }
});
```

I dont know why awaiting the mongodb operation will cause the ```AsyncIterator``` can not emit ```{ value: undefined, done: true }``` when there are no field left.

**Comment by Eomm** [comment]
I would try to switch to callback style in order to understand what is causing the issue.

Your code seems right to me too, I just assume that mongo dB has been set with the default database instead of selecting one

**Comment by climba03003** [comment]
I found the problem. It is just a stupid mistake. The order of plugin registration is not in the correct order. Although it is fine in the logging output, but it is not in the code execution.

Thanks for your help. I am closing this issue.

**Comment by climba03003** [comment]
When I switch back to callback style, it result the same.
No clue why it is happening.

The verification code work fine in other routes without the ```AsyncIterator```.

**Comment by salmanm** [comment]
I can't reproduce it either, tried various things.

@climba03003 It'd be really helpful if you could
- Post a repo with minimal code that reproduces this issue. 
- Post the exact POST request you're making to the `/import` endpoint.

**Comment by climba03003** [comment]
> 
> 
> I can't reproduce it either, tried various things.
> 
> @climba03003 It'd be really helpful if you could
> 
>     * Post a repo with minimal code that reproduces this issue.
> 
>     * Post the exact POST request you're making to the `/import` endpoint.
After I upgrade all the modules to latest version, the issue is solved.
Maybe some of the PR solve this problem.

I will close this issue, thank you for your help.

**Comment by climba03003** [comment]
@salmanm 
If you still want to find out the root cause here is the [repo](https://github.com/climba03003/fastify-multipart-issue-188)
I have used exact version for the modules in order to simulate the issue.

Routes
/signin
username: username
password: password

/withoutHandler
/withHandler

this two route is used to test behavior between with or without the validation handler
