### ISSUE TITLE
large file upload memory

### ISSUE THREAD

**Issue by dsun9** [fastify/fastify-multipart#19]
Hi I'm migrating from koa js  to fastify-multipart a page of uploading file. when use fastify-multipart, uploading a 1.6 gb file to server folder, the memory usage is much higher than koa js 800 mb vs 50 mb

with koa js i created a readstream, but with fastify-multipart, I'm not sure how to do that. 

Thanks

**Comment by mcollina** [comment]
Interesting, the code in the README should handle backpressure correctly. Can you please past a snippet of what you are doing with this module vs koa?

**Comment by dsun9** [comment]
koa js

		const file = ctx.request.body.files.file;
		const reader = fs.createReadStream(file.path);
		const stream = fs.createWriteStream(path.join(os.tmpdir(), Math.random().toString()));
		reader.pipe(stream);

fastify-multipart

			file.pipe(stream);

**Comment by mcollina** [comment]
@dsun9 can you please upload the full code?
The koa code is doing something completely different, it's copying one file from a location to another.

https://github.com/fastify/fastify-multipart/pull/20 checks that uploading a 1 GB file does not balloon the memory.

**Comment by dsun9** [comment]
still used 555675648
async function upload (request, reply) {
		const mp = request.multipart(handler, function (err) {
			reply.redirect('/upload.html');
		})
		const stream = fs.createWriteStream(path.join(os.tmpdir(), Math.random().toString()));

		// mp is an instance of
		// https://www.npmjs.com/package/multipart-read-stream

		mp.on('field', function (key, value) {
			console.log('form-data', key, value)
		})

		function handler (field, file, filename, encoding, mimetype) {
			console.log('in dao: ',process.memoryUsage().rss);
			pump(file, stream)			
			console.log('in dao: ',process.memoryUsage().rss);
			console.log('uploading %s -> %s', file.name, stream.path);
		}
}

**Comment by mcollina** [comment]
```
		console.log('in dao: ',process.memoryUsage().rss);
		pump(file, stream)			
		console.log('in dao: ',process.memoryUsage().rss);
```

this is not checking after the file has been saved you should add a a function at the end of `pump`, that will be called when the file has been processed.

**Comment by dsun9** [comment]
Thanks. there are 2 issues in my case,
1. during processing, I don't want consume that much memory. koa js seems to copy the file to a temp dir and made the path available so a readstream can be created

2.after processed, the memory stayed high for quite long. 
      a. without changing the checking, I uploaded a small file and checked the logging
      b. I also used windows performance monitor as a second witness

I'm wondering if "file" in lines below are a readstream.
pump(file, stream) or file.pipe(stream)

**Comment by mcollina** [comment]
file is a [`Readable`](https://nodejs.org/api/stream.html#stream_readable_streams).

Can you please upload a full example to demonstrate your problem?

**Comment by dsun9** [comment]
I actually followed the example. the way to reproduce it is to upload file on the same machine or between 2 machines with high network bandwidth. otherwise, the symptom will be hidden as network is bottleneck.

**Comment by mcollina** [comment]
Can you please provide a full code example that exhibit the problem with steps to reproduce?

**Comment by dsun9** [comment]
Thanks. I actually followed the example. the way to reproduce it is to upload file on the same machine (localhost) or between 2 machines with high network bandwidth. otherwise, the symptom will be hidden as network is bottleneck.
I used windows performance monitor to watch the memory usage

that said, below is the html I used,

<!DOCTYPE html>
<html>
<head>
  <title>Upload</title>
  <style>
    body {
      padding: 50px;
      font: 14px Helvetica, Arial;
    }
  </style>
</head>
<body>
  <h1>File Upload</h1>
  <p>Try uploading multiple files at a time.</p>
  <form action="/upload" method="post" enctype="multipart/form-data">
    <input type="file" name="file" multiple>
    <input type="submit" value="Upload">
  </form>
</body>
</html>

Thanks

**Comment by mcollina** [comment]
Confirmed, I used this to reproduce:

```js
'use strict'

const http = require('http')
const Readable = require('stream').Readable
const FormData = require('form-data')
const pump = require('pump')
const knownLength = 1024 * 1024 * 1024

function next () {
  var total = knownLength
  const form = new FormData({ maxDataSize: total })
  const rs = new Readable({
    read (n) {
      if (n > total) {
        n = total
      }

      // poor man random data
      // do not use in prod, it can leak sensitive informations
      var buf = Buffer.allocUnsafe(n)
      this.push(buf)

      total -= n

      if (total === 0) {
        this.push(null)
      }
    }
  })


  form.append('upload', rs, {
    filename: 'random-data',
    contentType: 'binary/octect-stream',
    knownLength
  })

  var opts = {
    protocol: 'http:',
    hostname: 'localhost',
    port: 3000,
    path: '/upload',
    headers: form.getHeaders(),
    method: 'POST'
  }

  var req = http.request(opts, next)

  pump(form, req)
}

next()
```
