### ISSUE TITLE
Truncated value inconsisteny

### ISSUE THREAD

**Issue by vsnu1995** [fastify/fastify-multipart#194]
## 🐛 Bug Report

Limiting filesize on req.file() truncates the file but data.file.truncated is set as false. Works fine when limit is 20000 and larger file is posted. But when limit is higher truncated is not setting to true, file gets truncated to the specified filesize.

## To Reproduce

```js
//Global limits
limits: {
		fieldNameSize: 100,
		fieldSize: 1000000,
		fields: 10,
		fileSize: 10000000,)
		files: 1,
		headerPairs: 20, 
	},

const data = await req.file({ limits: { fileSize: 100000 } });
if (data.file.truncated) {
 throw err;
}
```

## Expected behavior
Error must be thrown for all files with size > fileSize

## Your Environment

- *node version*: v14.15.0
- *fastify version*: 3.9.2
- *os*: Linux
- *fastify-multipart*: 3.3.1

**Comment by mcollina** [comment]
Can you please upload a _runnable_ example to reproduce?

Also, would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by vsnu1995** [comment]
```const fastify = require('fastify')({ logger: true })

fastify.register(require('fastify-multipart'), {
	limits: {
		fieldNameSize: 100,
		fieldSize: 1000000,
		fields: 10,
		fileSize: 10000000,
		files: 1,
		headerPairs: 20,
	},
});

fastify.route({
  method: 'POST',
  url: '/',
  handler: async (request, reply) => {
		const data = await request.file({limits: { fileSize: 100000 }}); //Uploading a file larger than 100kb returns success
		if(data.file.truncated) {
			return { status: 'failed'}
		}
		return { status: 'success'}
  }
})

const start = async () => {
  try {
    await fastify.listen(3000)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()```

**Comment by vsnu1995** [comment]
Oh it seems like i missed the part of data.file promise not getting fulfilled till its consumed. Its working as expected when i consume.
