### ISSUE TITLE
the multipart data is being reinserted recursively for each property

### ISSUE THREAD

**Issue by ionutale** [fastify/fastify-multipart#195]
## 🐛 Bug Report

it looks like the body is being reinserted into the text field
<img width="699" alt="Schermata 2021-01-17 alle 10 12 09" src="https://user-images.githubusercontent.com/2562455/104836229-c523a980-58ac-11eb-9c49-68ebd882a2d5.png">

## To Reproduce

create a plugin with the code bellow:
```js

const createLayout = {
  method: 'POST',
  url: '/layouts',
  schema: {
    body: {
      
    }
  },
  handler: async (request, reply) => {

   // insert breakpoint here for request.body inspection 
    console.log(request.body)

    reply
      .header('x-layout-id', 'layoutid')
      .code(201)
      .send(request.body)
  }
}

module.exports = async (fastify, opts) => {
  fastify.register(require('fastify-multipart'), {
    attachFieldsToBody: true,
    // sharedSchemaId: '#layoutCreateSchema',
    limits: {
      fieldNameSize: 100, // Max field name size in bytes
      fieldSize: 1000000, // Max field value size in bytes
      fields: 10,         // Max number of non-file fields
      fileSize: 100,      // For multipart forms, the max file size
      files: 1,           // Max number of file fields
      headerPairs: 2000   // Max number of header key=>value pairs
    }
  })

  fastify.route(createLayout)

}

```

## Expected behavior

```js
body: {
  shortName: "tin tin",
  image: { ...imageObjectMultipart }
}
```

## Your Environment

- *node version*:  14
- *fastify version*: >=^3.9.2
- *os*: Mac
``` 
 "fastify": "^3.9.2",
  "fastify-mongodb": "^2.0.1",
  "fastify-multipart": "^3.3.1",
  "fastify-swagger": "^3.5.0",
```

**Comment by mcollina** [comment]
Can you please provide a _runnable_ example, i.e. something we can `node bug.js` and see the failure?

**Comment by StarpTech** [comment]
What's the issue here? It's correct that a field has a reference to all fields for easier access.

**Comment by ionutale** [comment]
@StarpTech ok, so this is by design?
do i still have to provide a bug.js example?

**Comment by StarpTech** [comment]
Yes, it's by design but we are open to improvements. @mcollina Maybe we should always use the `body` property when attaching data.

**Comment by ionutale** [comment]
It would be nice to be able to opt-out of this, maybe with options object

**Comment by ionutale** [comment]
Also it would be nice to opt-out of "field-type"
It would be nice to have `key:val` pair  instead of "field-type"

For me the name of the field is redundant, and the truccated flag, should be documented, and optional, but not intrusive.
I think you created the  "field-type" for security reasons, but if i use the validation, with "pattern" prop, i take care of the security

<img width="700" alt="Schermata 2021-01-20 alle 08 22 48" src="https://user-images.githubusercontent.com/2562455/105141224-2049dc00-5af9-11eb-955c-31b18aa6fe1c.png">

it would be nice to opt-out and have manual control over validation

**Comment by StarpTech** [comment]
@ionutale I can't follow you. Again, what is the issue?
