### ISSUE TITLE
fileSize limit on fastify-multipart did not throw error

### ISSUE THREAD

**Issue by yofriadi** [fastify/fastify-multipart#196]
I don't know if I use it correctly or not but it is just pass through if I passing file with size higher than limit.

```js
/*
 * other code
 */

fastify.post('/upload', async function (req, reply) {
    const data = await req.file({
      limits: {
        fileSize: 1 * 1024 * 1024,  // 1mb limit
      }
    })

    await pump(data.file, fs.createWriteStream(data.filename))

    reply.send()
})
```

It write file to my directory, when I expect it to throw error

* *node version*: 14.15.3
* *fastify version*: 3.9.2
* *fastify multipart version*: 3.3.1
* *os*: WSL

**Comment by mcollina** [comment]
Apparently in https://github.com/fastify/fastify-multipart/blob/master/test/multipart.test.js we are testing that we are _not_ throwing an error, but there is a `file.truncated` property instead.

@StarpTech wdyt?

**Comment by StarpTech** [comment]
Yes, busboy marks a file with `truncated` when the file limit was reached. In my opinion, an error should be thrown but I can't remember why we didn't implement it. According to busboy the library will only emit a `limit` event on the `file` object.

**Comment by mcollina** [comment]
> Yes, busboy marks a file with truncated when the file limit was reached. In my opinion, an error should be thrown but I can't remember why we didn't implement it. According to busboy the library will only emit a limit event on the file object.

I guess we should error this.

**Comment by kamikazechaser** [comment]
I did notice this. In my case I am doing something like:

```js
    const buffer = await data.toBuffer();

    if (data.file.truncated) {
      // FILE SIZE EXCEED
    }
```

Unfortunately with this approach someone can upload a very large file (which in turns consumes a lot of memory). Such an error should be thrown at the earliest.

**Comment by StarpTech** [comment]
> Unfortunately with this approach someone can upload a very large file (which in turns consumes a lot of memory). Such an error should be thrown at the earliest.

That's not accurate. Busboy the underlying library will abort it.

**Comment by kamikazechaser** [comment]
> Busboy the underlying library will abort it.

Oh thanks for the heads up!

**Comment by climba03003** [comment]
I just faced the same issue today and used an hour for debugging this issue until I check the `README.md`.

In order to handle the case properly, I think we should return status code 413 instead of throwing an error. The developer and the client which use the API can visualize the problem immediately when they see status code 413 (Payload Too Large).

**Comment by mcollina** [comment]
@climba03003 how would you solve this?

**Comment by climba03003** [comment]
For now, throwing error is the simplest solution.
We can introduce an option `throwFileLimit` to enable throwing behavior and which the default is `false`.
If we manage to bump an major, change it to default `true`.

**Comment by mcollina** [comment]
Could you send a PR? That seems reasonable. I'd actually consider this a bug and ship as a minor, with a flag to not throw.

**Comment by yofriadi** [comment]
hi all, I just try the new version 4.0.0 but unfortunately the problem still exist when using `req.file`, `req.files` and `req.parts` but works when using `req.saveRequestFiles`.

can anyone confirm this, thank you

**Comment by climba03003** [comment]
Can you provide the code snippets? Have you tried a clean installation of `node_modules` as `yarn.lock` or `package-lock.json` will lock the version of package.

**Comment by eKulshan** [comment]
He everyone, also tried 4.0.0 version and run into the same problem as @yofriadi.
**Fastify**
`export default () => {
  const app = fastify({
    logger: {
      prettyPrint: true,
    },
  });
  app.register(fastifyMultipart, {
    throwFileSizeLimit: true,
    limits: {
      files: 1,
      fileSize: 10000,
    },
  });
  addRoutes(app);

  return app;
};`

**Route** 
`export default (app: FastifyInstance) => {
  app
    .get('/', (_request, reply) => {
      reply.send('spelling-kata');
    })
    .post('/spell/fix', async (request, reply) => {
      try {
        const data = await request.file();
        const reqBuffer = await data.toBuffer();

        const text = reqBuffer.toString();
        const fixedText = await fixSpelling(text);
        const resBuffer = Buffer.from(fixedText, 'utf-8');

        return reply
          .headers({
            'Content-Disposition': `attachment; filename=${data.filename}`,
            'Content-Type': 'text/plain',
          })
          .send(resBuffer);
      } catch (error) {
        return reply.code(500).send(error.message);
      }
    });
};`

**Comment by mcollina** [comment]
Given that the tests are passing, it would be good to have a self-runnable example that reproduces the problem.

**Comment by StarpTech** [comment]
I think I found the issue. It's a race condition between the first emitted file and error. `await file()` returns the file immediately but the error is thrown asynchronously and at that moment the consumers won't consume the second event because they expect a single file. We have to ensure internally that all [events](https://github.com/fastify/fastify-multipart/blob/master/index.js#L297) are consumed.

It works for `req.saveRequestFiles``due to that exact reason because all events are consumed and it is guaranteed that the error is handled.

**Comment by StarpTech** [comment]
I think the current behavior is correct because we can only guarantee error handling when we iterate over the entire multipart stream until `onEnd` is called. In all other cases, the user has to subscribe to `file.on("limit")`. From DX API perspective `req.file` is error prone because it will never report the final error.

> hi all, I just try the new version 4.0.0 but unfortunately the problem still exist when using req.file, req.files and req.parts but works when using req.saveRequestFiles.

I couldn't reproduce it. It is only valid for `req.file`. Please provide a reproducible example.

**Comment by brainrepo** [comment]
I tried to propose a feat that can help to manage the case above. Can I have some feedback about the approach?

**Comment by abcfy2** [comment]
I met the same error. I use the latest version `4.0.7`, but still happened.

```ts
    // fileSize = 40MB
    const data = await request.file({limits: {fileSize: 41943040}});
    const fileStream = data.file;
```

When I try to upload a very large file like:

```sh
curl -F 'file=@BIG_FILE' localhost:3006/upload
```

It's success without any exception. But the uploaded file is only 40 MB, what happened?

**Comment by abcfy2** [comment]
OK. I find the issue: https://github.com/fastify/fastify-multipart/issues/250
