### ISSUE TITLE
Typescript definition for onFile is incorrect when `attachFieldsToBody` is true

### ISSUE THREAD

**Issue by dancoates** [fastify/fastify-multipart#201]
## 🐛 Bug Report

The definition for the onFile option specifies that it is passed multiple params:

```ts
onFile?: (fieldName: string, stream: Readable, filename: string, encoding: string, mimetype: string, body: Record<string, BodyEntry>) => void | Promise<void>;
```
https://github.com/fastify/fastify-multipart/blob/master/index.d.ts#L103

But when the `attachFieldsToBody` is set to true `onFile` is called with a single parameter:

https://github.com/fastify/fastify-multipart/blob/master/index.js#L143

## Expected behavior
There should either be a different option that is called with each file when `attachFieldsToBody` is true or the `onFile` function should have a consistent function signature.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by dancoates** [comment]
I'd be happy to, but not sure what direction you'd like to go in. I think the cleanest solution would be to update the code so that `onFile` is always called with the same params but that would be a breaking change.

**Comment by mcollina** [comment]
I think updating the types is the simplest option.
