### ISSUE TITLE
Recursive field attachements?!

### ISSUE THREAD

**Issue by yaneony** [fastify/fastify-multipart#225]
I wonder why circular fields attachement is being done? If you submit form, you will notice that each field has instance of "fields" which are recursive... 

https://github.com/fastify/fastify-multipart/blob/master/index.js#L367
https://github.com/fastify/fastify-multipart/blob/master/index.js#L400

Any point for doing that? That only do increase memory consumption...

**Comment by climba03003** [comment]
As mention in https://github.com/fastify/fastify-multipart/issues/195 is the be design behavior.
