### ISSUE TITLE
Not able to get multiple files

### ISSUE THREAD

**Issue by HoaX7** [fastify/fastify-multipart#230]
Im not able to upload multiple files, req.files() just says its an Empty async object.

here's my code,

i'll just post the snippets 

// app.js
require fastify and stuff

fastify.register(require("fastify-multipart"))

register routes as well
listen to port

// routes and the func im trying to access the files
fastify.post("/uploads", async (req, res) => {
    await req.files() // blank
    await req.file() // returns 1 file
})

i also tried adding { attachFieldsToBody: true }, { addToBody: true |
ofc when i do these i get the file fields in an array in the body object. but i want the stream. 
But in the same route await req.file() returns 1 file
and im sending form data with same fieldname for both files

**Comment by SudoDios** [comment]
please write a sample of this

**Comment by climba03003** [comment]
Please use `fastify/help` or visit Discord for helps.
