### ISSUE TITLE
NodeJS 16 support

### ISSUE THREAD

**Issue by alex-outsourci** [fastify/fastify-multipart#232]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.15.1

### Node.js version

16.1.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

"saveRequestFiles()" never returns on NodeJS 16.1, but it works great on NodeJS 14.17.0

### Steps to Reproduce

```
if (req.isMultipart()) {
    console.log('Saving files');
    const files = await req.saveRequestFiles();
    console.log('Saved files'); //<--- this line never fires on NodeJS 16.1.0
    //  ... 
}
```

### Expected Behavior

Expect it works the same as on NodeJS 14.x

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by simoneb** [comment]
I started looking into this issue in https://github.com/fastify/fastify-multipart/pull/235. I haven't found a solution yet but I narrowed down the point where it happens. It seems to be somewhat related to the `highWaterMark` setting of the write stream created to save files to the file system. Increasing the value of that setting to something larger than the size of the files uploaded in the tests seems to address it, but clearly this is not a solution as we can't just set it to an arbitrary large value. 

Why it happens in Node 16 and not 14 I haven't figured out. Doing something similar in a standalone repro which doesn't involve the plugin or busboy doesn't show any inconsistencies in behavior, suggesting that it's something that we're doing in this repo or busboy that's causing it.

**Comment by simoneb** [comment]
The boundary value causing the issue seems to be 16k (the default value for `highWaterMark` in streams). 

This is the (non) repro, showing that using plain Node.js without this plugin and all the third party code involved the issue doesn't happen:

```js
const { Readable } = require("readable-stream");
const { pipeline: pump } = require("stream/promises");
const { createWriteStream } = require("fs");
const path = require("path");
const os = require("os");
const hexoid = require("hexoid");

const toID = hexoid();

async function run() {
  const filepath = path.join(os.tmpdir(), toID());

  const target = createWriteStream(filepath);

  await pump(getMockFileStream(16384), target);

  console.log("written to", filepath);
}

run();

// this is the same function we use to generate arbitrary
// read streams in tests
function getMockFileStream(length) {
  let total = length;

  const rs = new Readable({
    read(n) {
      if (n > total) {
        n = total;
      }

      const buf = Buffer.alloc(n).fill("x");
      this.push(buf);

      total -= n;

      if (total === 0) {
        this.push(null);
      }
    },
  });

  return rs;
}

```

**Comment by simoneb** [comment]
Quick update. I tried a more complete repro which involves Busboy as well but still can't reproduce. This suggests that the problem is probably somewhere in the plugin code. I suspect the async iterators we use to loop through the files.
