### ISSUE TITLE
NodeJS.ReadableStream used over Readable

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify-multipart#247]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.x.x

### Plugin version

4.0.6

### Node.js version

16.3.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

According to https://nodejs.org/api/stream.html#stream_readable_wrap_stream:

```
When using an older Node.js library that emits 'data' events and has a stream.pause() method that is advisory only, the readable.wrap() method can be used to create a Readable stream that uses the old stream as its data source.

It will rarely be necessary to use readable.wrap() but the method has been provided as a convenience for interacting with older Node.js applications and libraries.
```

So usage of `NodeJS.ReadableStream` seems to be more of a legacy behaviour, and it causes issues when e. g. trying to pass this stream to Azure Storage, which expects to get Readable instead.

### Steps to Reproduce

Call req.file().file. See TS signature of fastify-multipart:

```
export interface MultipartFile {
  toBuffer: () => Promise<Buffer>,
  file: NodeJS.ReadableStream,
  filepath: string,
  fieldname: string,
  filename: string,
  encoding: string,
  mimetype: string,
  fields: MultipartFields
}
```

### Expected Behavior

Multipart file should be Readable

**Comment by climba03003** [comment]
I think it should be identical to `busboy` typing as we are using `busboy` underlay.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/busboy/index.d.ts#L41

**Comment by mcollina** [comment]
I think this is only a TS problem.

**Comment by kibertoad** [comment]
I will open a PR both for busBoy types and here then, because yes, in reality we do get a Readable.
