### ISSUE TITLE
limits.fileSize not working when greater than a specified value

### ISSUE THREAD

**Issue by abcfy2** [fastify/fastify-multipart#250]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.8.1

### Plugin version

4.0.7

### Node.js version

14.17.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Manjaro 21

### Description

When fileSize is greater than a specified value, it will not throw exception when upload large file.

### Steps to Reproduce

Here is the sample code just from README

```js
const fastify = require('fastify')()
const fs = require('fs')
const util = require('util')
const path = require('path')
const { pipeline } = require('stream')
const pump = util.promisify(pipeline)

fastify.register(require('fastify-multipart'))

fastify.post('/', async function (req, reply) {
  // process a single file
  // also, consider that if you allow to upload multiple files
  // you must consume all files otherwise the promise will never fulfill
  console.log('before req file');
  // {limits: {fileSize: 1024}}
  const data = await req.file({limits: {fileSize: 40 * 1024}})
  console.log(data);
  console.log('after req file');

  // to accumulate the file in memory! Be careful!
  //
  // await data.toBuffer() // Buffer
  //
  // or

  console.log('before pump')
  await pump(data.file, fs.createWriteStream(data.filename))
  console.log('after pump')
  // be careful of permission issues on disk and not overwrite
  // sensitive files that could cause security risks
  
  // also, consider that if the file stream is not consumed, the promise will never fulfill

  reply.send()
})

fastify.listen(3000, err => {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})
```

Test with `curl`:

```sh
curl -v -F 'file=@BIG_FILE' localhost:3000/
```

When `fileSize` is a small one like `40 * 1024`(40KB), it's working, response:

```json
{"statusCode":413,"code":"FST_REQ_FILE_TOO_LARGE","error":"Payload Too Large","message":"request file too large, please check multipart config"}
```

But when `fileSize` is a large one like `40 * 1024 * 1024`(40MB), it's not working, the file is uploaded successfully, but the uploaded file is truncated to 40MB only.

### Expected Behavior

`limits.fileSize` should working as expect.

**Comment by mcollina** [comment]
Thanks for reporting! This looks like a bug. Would you like to send a PR with a fix?

**Comment by abcfy2** [comment]
I'm not very familiar with busboy, but I will give a try.

**Comment by abcfy2** [comment]
Seems that when `fileSize` is large, the `file.truncated` is `false` first.

```js
// ...
  const data = await req.file({limits: {fileSize: 1024*1024*40}, throwFileSizeLimit: true})
  const file = data.file;
  console.log('file.truncated before pump: ' + file.truncated)
  await pump(data.file, fs.createWriteStream(data.filename))
  console.log('file.truncated after pump: ' + file.truncated);
// ...
```

Output:

```sh
file.truncated before pump: false
file.truncated after pump: true
```

**Comment by leorossi** [comment]
@abcfy2 I am working on this and found this interesting thing.

I am using a 4Mb file to test using your code and `curl` command.

- while `limits.fileSize <= 65378` the code  returns correctly a `FST_REQ_FILE_TOO_LARGE`
- when `limits.fileSize > 65378` the error is not thrown and `pump(..)` writes a file with the same size as the `fileSize` option (likes it saves the first chunk emitted by busboy).

**Comment by leorossi** [comment]
After some more research `65378` is `65536` (first chunk read) - 157  (the bytes needed for the multipart preamble).

So basically when we have more than 1 chunk the error is not thrown

**Comment by leorossi** [comment]
So here's my conclusions on this: the library work as expected but maybe docs should be slightly more clear on this. 

```
 await pump(data.file, fs.createWriteStream(data.filename))
```
this line does _NOT_ guarantee that the file has been completely written on disk. In fact, after this line you should check `data.file.truncated`, if it's `false` then all the file has been streamed, otherwise the limit has been reached.

```
const filename = data.filename + 'output';
await pump(data.file, fs.createWriteStream(filename))
if (data.file.truncated) {
  console.log('file is truncated');
  fs.unlinkSync(filename);
  return reply.send(new fastify.multipartErrors.FilesLimitError());
} else {
  return reply.send({ message: 'file accepted' });
}
```

Alternatively you can also use `req.saveRequestFiles({ limits: { fileSize: YOUR_FILESIZE_LIMIT } })` and that would handle the error for you.

I will update the docs and create a PR to underline this fact.

**Comment by mcollina** [comment]
I have a feeling we should be destroying the stream with an error if the file is truncated. Maybe behind an option?

**Comment by simoneb** [comment]
@abcfy2 can you please check if the updated docs at https://github.com/fastify/fastify-multipart/pull/259 clarify the way this is intended to work?
