### ISSUE TITLE
Typescript data.fields returns wrong type.

### ISSUE THREAD

**Issue by abcfy2** [fastify/fastify-multipart#251]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.8.1

### Plugin version

4.0.7

### Node.js version

14.17.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Manjaro 21

### Description

Seems that the type define of `fields` is not correct.

```ts
export type Multipart<T = true> = T extends true ? MultipartFile : MultipartValue<T>;
```

Seems this make `Multipart` type is always `MultipartFile`, never `MultipartValue`.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/5327677/124133259-3bf7dc00-dab4-11eb-853d-2fe5b10f2fdf.png)
![image](https://user-images.githubusercontent.com/5327677/124133711-af99e900-dab4-11eb-968b-f5e1bbdcb81a.png)

![image](https://user-images.githubusercontent.com/5327677/124133332-4f0aac00-dab4-11eb-80b7-c59ca30bfddd.png)

Building error:

```sh
TS2339: Property 'value' does not exist on type 'MultipartFile | MultipartFile[]'.
  Property 'value' does not exist on type 'MultipartFile'.
```

### Expected Behavior

`data.fields.{field_name}` should able to return `MultipartValue` type.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by abcfy2** [comment]
OK. If I have enough time, I will give a try.

**Comment by climba03003** [comment]
Typescript have no way to know which is the suitable type for fields as it is mixed with both `file` and `field`.

One of the usage is type augmentation if you have only single endpoint for file handling.
```ts
declare module 'fastify-multipart' {
  interface MultipartFields {
    foo: Multipart<string> // is will be value
    file: Multipart<true>
  }
}
```

**Comment by sanzhardanybayev** [comment]
> Typescript have no way to know which is the suitable type for fields as it is mixed with both `file` and `field`.
> 
> One of the usage is type augmentation if you have only single endpoint for file handling.
> 
> ```ts
> declare module 'fastify-multipart' {
>   interface MultipartFields {
>     foo: MultipartValue<T>
>     file: MultipartFile
>   }
> }
> ```
> 
> Other way is type casting.

I have sort of the same issue. But redeclaration specifically for the **file** property doesn't work. TS keep reading module's typings.  

The only was using **type casting** as you suggested.

**Comment by realfresh** [comment]
For anyone wondering what to do in the case of a single file upload with extra fields

```typescript
type BodyFields = {
  foo: string
  bar: string
}

const data = await req.file();
const file = await data.toBuffer();
const fields = data.fields as any as {
    [key in keyof BodyFields]: {
        value: BodyFields[key];
    };
};
const foo = fields.foo.value;
const bar = fields.bar.value;
```

**Comment by gabrielrufino** [comment]
Any updates?

**Comment by mcollina** [comment]
> Any updates?

@gabrielrufino I haven't seen a PR from you yet.
