### ISSUE TITLE
limits.fileSize when set global fileSize doesn't get limited

### ISSUE THREAD

**Issue by veritem** [fastify/fastify-multipart#256]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.0.0

### Plugin version

4.0.5

### Node.js version

14.17.3

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

I'm setting up the plugin to limit to file size of 2 MB, it doesn't work this is my current setup
![image](https://user-images.githubusercontent.com/53856673/125168235-befbef00-e1a4-11eb-8f0e-efeb650266e9.png)

### Steps to Reproduce

As documented here `limit.fileSize` didn't work for me when set global(On plugin registration)

### Expected Behavior

The plugin should have limited to the size I've specified during its registration

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by climba03003** [comment]
I think it should be the problem of typo?

Your screenshot is `fieldSize` which will not and should not limit the file size.

**Comment by veritem** [comment]
> I think it should be the problem of typo?
> 
> Your screenshot is `fieldSize` which will not and should not limit the file size.
sorry, I tried a bunch of stuffs which didn't work screenshot fixed

**Comment by simoneb** [comment]
@veritem can you please check if the updated docs at https://github.com/fastify/fastify-multipart/pull/259 clarify the way this is intended to work?
