### ISSUE TITLE
File size limit still not working 

### ISSUE THREAD

**Issue by rhadamez** [fastify/fastify-multipart#263]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.1

### Plugin version

4.0.7

### Node.js version

16.5.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

Hey,

The option of "fileSize" limit is not being respected: it is not throwing and exception when upload large file. I have found the issue #250 and #256, but they are closed and the bug still around.

### Steps to Reproduce

I have created a very simple repository to reproduce:

https://github.com/rhadamez/fastify-upload-file

### Expected Behavior

It is expected an exception referred about the size.

**Comment by Eomm** [comment]
I have added some code comments to explain what is happening:

```js
server.register(fastifyMultipart, {
    limits: {
        fileSize: (1024 * 1024) * 0.5 /* 0.52MB */
    }
})

server.post('/upload', async (req, res) => {
    const file = await req.file()
    // at this stage, the `file.file` is not consumed, it means that the request stream is in PAUSE state 
    // so the data are not flowing into the server.
    // right now the fileSize check has been PASSED because there is only one chunk of data in memory.

    // whenever you consume the file.file stream, the data are being collected, so the fileSize check HAPPEN.
    // since the file.file is a stream, you need to listen to the event `limit` 
    // or check for the `file.file.truncated` flag (as documented) 
    // https://github.com/fastify/fastify-multipart#usage read the NOTE at the bottom
})
```

I have arranged a PR to ease this check calling `await file.file.toBuffer()`, but the keep away is: consume the stream or the `fileSize` check won't execute
