### ISSUE TITLE
Cannot parse body if no file is sent

### ISSUE THREAD

**Issue by isgj** [fastify/fastify-multipart#266]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.2

### Node.js version

14, 16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

If I send a multipart request only with simple data like foo=bar (without any file in the body) the library is unable to parse and return the body.

### Steps to Reproduce

Example of a request from insomnia

![image](https://user-images.githubusercontent.com/20517048/131629731-1ad32248-89d9-4a18-8a2d-5c6a1791e5d7.png)

### Expected Behavior

```ts
req.isMultipart() // returns true
const data = await req.file() // or other methods that parse the body
// data is always undefined, I expect here data to be {"foo": "bar"} (the right format used by lib)
```

**Comment by climba03003** [comment]
Please use `request.parts` for the fields data. Remember, it is a `AsyncIterator`.
```js
fastify.post('/upload/raw/any', async function (req, reply) {
  const parts = req.parts()
  for await (const part of parts) {
    if (part.file) {
      await pump(part.file, fs.createWriteStream(part.filename))
    } else {
      console.log(part)
    }
  }
  reply.send()
})
```

**Comment by isgj** [comment]
Thank you
