### ISSUE TITLE
Update README with relevant information from callback.md file

### ISSUE THREAD

**Issue by radomird** [fastify/fastify-multipart#276]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi,
I would like to propose a suggestion. In the Readme file there is some missing information regarding schema validation that is **_still relevant in the new API_** (and I think it should be there as it is very useful).

The missing information can be found at the end of the [callback.md](../blob/master/callback.md) file, I've pasted it below for reference:

> The sharedSchemaId parameter must provide a string ID and a shared schema will be added to your fastify instance so you will be able to apply the validation to your service like this:

```
fastify.post('/upload', {
  schema: {
    body: {
      type: 'object',
      required: ['myStringField', 'myFilenameField'],
      properties: {
        myStringField: { type: 'string' },
        myFilenameField: { type: 'array', items: 'MultipartFileType#' }
    }
  }
}, function (req, reply) {
  reply.send('done')
})
```

> The shared schema added will be like this:

```
{
  type: 'object',
  properties: {
    encoding: { type: 'string' },
    filename: { type: 'string' },
    limit: { type: 'boolean' },
    mimetype: { type: 'string' }
  }
}
```

**Comment by radomird** [comment]
> The readme contains
> 
> > If you enable attachFieldsToBody and set sharedSchemaId a shared JSON Schema is added, which can be used to validate parsed multipart fields.
> 
> how could we write it clearer?

That part is really clear, but the information that I quoted from callback.md file is actually missing from the readme.

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by radomird** [comment]
@mcollina Sure, will do that.
