### ISSUE TITLE
Improve docs: add more details for JSON schema validation

### ISSUE THREAD

**Issue by radomird** [fastify/fastify-multipart#277]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

When validating non-file fields in the body and **NOT** using the shared schema, according to the plugin documentation, we can validate the fields by using the following syntax:
```
body: {
  type: 'object',
  properties: {
    hello: {
      properties: {
        value: { 
          type: 'string',
        }
      }
    }
 }
```

However one would expect that for the non-file fields (like this for example: ```{ "hello": "world"}``` ) the JSON schema for validation would be:
```
body: {
  type: 'object',
  properties: {
    hello: {
      type: 'string'
    }
  }
}
```
just like it's mentioned in the [fastify docs](https://www.fastify.io/docs/latest/Validation-and-Serialization/).

However, the plugin converts the non-file fields from this:
 ```
{ "hello": "world"}
``` 
to this: 
```
{ 
  hello: {
    fieldname: "hello",
    value: "world",
    fieldnameTruncated: false,
    valueTruncated: false,
    fields: body
  }
}
```
and therefore the validation schema on top (from the plugin docs) makes sense.

However, **the problem is that this conversion is not mentioned anywhere** in the documentation and it's just really confusing and leads to issues like this: https://github.com/fastify/help/issues/525#issue-989998191

I would suggest to mention the conversion which would explain why is the validation schema defined like it is.

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by radomird** [comment]
@mcollina Sure, will do that.
