### ISSUE TITLE
Socket closed by remote peer

### ISSUE THREAD

**Issue by alizahid** [fastify/fastify-multipart#29]
Had this problem since I upgraded to `0.4.0`.

When I upload a file, the socket is immediately closed by the server. The file upload happens in the background.

I need to wait for the upload to complete, and then whatever processing to be done, so I can return the final url from AWS. I thought I was doing something wrong, but I just tried the sample code in a new project and it has the same behavior.

**Comment by mcollina** [comment]
Can you provide steps to reproduce?

**Comment by mcollina** [comment]
This is already out in 0.4.1.

**Comment by alizahid** [comment]
Ah. I was watching the repo for a tag release. Thank you so much! 🍻
