### ISSUE TITLE
If I send file using form-data, then file automatically saved in storage, I want to call onFile only for specific route not for all by mistake file form-data.

### ISSUE THREAD

**Issue by i-coderdev** [fastify/fastify-multipart#298]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the issue has not already been raised

**Comment by Eomm** [comment]
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.
