### ISSUE TITLE
Multipart: Boundary not found

### ISSUE THREAD

**Issue by tc-root-user** [fastify/fastify-multipart#304]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.1

### Plugin version

5.2.0

### Node.js version

16.5.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

When the file limit size is set, then headers are a mandatory prop. The code should be something like:

```js
await req.file({
    headers: { "content-type": "multipart/form-data" },
    limits: {
        fileSize: (1024 * 1024) * 55
    }
})
```

The issue begins with passing those content-type at the request (as they are mandatory now), then the server responds with error 500 and the message "Multipart: Boundary not found".

### Steps to Reproduce

1 - Make a file upload;
2 - Set some limit to the upload throught req.file(PROPS);
3 - Verify that the headers are mandatory now;
4 - Pass the respective header throught request;
5 - Try to do the upload;
6 - Observe that the server responds with error 500 with the message "Multipart: Boundary not found".

### Expected Behavior

The upload happens normally respecting the file size limit.

**Comment by kibertoad** [comment]
@Uzlopak

**Comment by climba03003** [comment]
The main problem is the user *must* not pass the `headers` to option.
https://github.com/fastify/fastify-multipart/blob/0e449a7346a52ad5c8a59166a52b34bfcbcd9f10/index.js#L321

The headers should be passed using `request.headers`.

My command here is correct, it is a breaking change if you force the user to pass the `headers`.
https://github.com/fastify/fastify-multipart/pull/300#discussion_r762502413

**Comment by kibertoad** [comment]
@tc-root-user Can you please check with 5.2.1?

**Comment by tc-root-user** [comment]
> @tc-root-user Can you please check with 5.2.1 (with removed explicit header)?`

Working as expected!
