### ISSUE TITLE
Canceled uploads are not propagated to the part.file FileReadStream

### ISSUE THREAD

**Issue by mccare** [fastify/fastify-multipart#315]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.3

### Plugin version

5.2.1

### Node.js version

16.13.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.1

### Description

When a user cancels the upload request, the cancel/destroy event is not propagated to the `part.file` FileReadStream. The request is not ended. Cleanup code that lives e.g. in the `finally` of my `try/catch` block is not called (e.g. to remove tempfiles).

### Steps to Reproduce

I've created a sample repo here https://github.com/mccare/multipart-upload-error-handling

* yarn install and run yarn dev
* `curl -i --limit-rate 100k -w '%{http_code}\n' -F video=@bigfile.binary -F events=@anotherbigfile.binary http://localhost:3000/upload `
* Terminate curl before request has gone through

The log files will show that the `finally` block is never reached. I'm assuming the request is not finished

### Expected Behavior

The code should throw some sort of error and the execution should at least reach the `finally` clause of my request handler.

I have added a `close` handler for `request.raw` to cancel/destroy the `part.file` Readable. This produces the expected results, but I don't know if that is the correct way to handle this.

**Comment by climba03003** [comment]
@Uzlopak do you have time to look at this issue? I think it is something related to both `busboy` and how request is ended.

**Comment by Uzlopak** [comment]
Hi, i arrived just few hours ago in Germany, where my Laptop is. I will have a look at it.

My assessment is close to yours. I think BusBoy-Stream has to listen to the close event and pass it down to each open partsStram.

**Comment by Uzlopak** [comment]
@climba03003 @mccare 
I checked it out. request.raw is calling unpipe on busboy
https://github.com/fastify/fastify-multipart/blob/635a523bdf1ae42bf8aa2191d6f10f11665e5930/index.js#L472

So it should make the trick to modify the code about here https://github.com/fastify/busboy/blob/6d8f8741cd5a9787fe7c4d1f1fb57bd165ad6c66/lib/types/multipart.js#L174 by adding in line 175
```javascript
        boy.on('unpipe', function () {
          file.destroy()
        })
```
Maybe also adding this makes sense.
```javascript
        boy.on('cancel', function () {
          file.destroy()
        })
        boy.on('destroy', function () {
          file.destroy()
        })
```

Canceling the upload results now in:

```
> upload-error@1.0.0 dev
> fastify start -w -l info -P app.js

13:45:14 ✨ Server listening at http://127.0.0.1:3000
13:45:15 ✨ incoming request POST xxx /upload
13:45:16 🚨 Error caught in main loop
13:45:16 🚨 Premature close 
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:371:5)
    at FileStream.onclose (node:internal/streams/end-of-stream:135:30)
    at FileStream.emit (node:events:402:35)
    at emitCloseNT (node:internal/streams/destroy:138:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:45:16 ✨ Finally finished in main loop
13:45:16 🚨 Premature close POST 500 /upload 
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:371:5)
    at FileStream.onclose (node:internal/streams/end-of-stream:135:30)
    at FileStream.emit (node:events:402:35)
    at emitCloseNT (node:internal/streams/destroy:138:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
{
  "err": {
    "type": "Error",
    "message": "Premature close",
    "stack": "Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close\n    at new NodeError (node:internal/errors:371:5)\n    at FileStream.onclose (node:internal/streams/end-of-stream:135:30)\n    at FileStream.emit (node:events:402:35)\n    at emitCloseNT (node:internal/streams/destroy:138:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "code": "ERR_STREAM_PREMATURE_CLOSE"
  }
}
```

Is this the requested behaviour?

@kibertoad

**Comment by Uzlopak** [comment]
Created corresponding PR
https://github.com/fastify/busboy/pull/81

**Comment by mccare** [comment]
I would expect the pipelining to throw an error since the readable was prematurely closed. So yes, something along these lines. If this is the correct/expected behaviour in regard to the type of exception, don't know.

What about using `pipeline` instead of `pipe`, so `pipeline(request, busboy)` instead of `request.pipe(busboy)`. That should at least do some error propapgation, but don't know if that fixes the problem or not.

**Comment by TriStarGod** [comment]
Hi @mccare , I also wanted to handle partial uploads.
I tried your `request.raw.on("close", ...` as outlined in your [sample](https://github.com/mccare/multipart-upload-error-handling/blob/master/routes/upload.post.js) but it would freeze and my call would be stuck on `Pending`. Without it, my post functions normally. Did this occur to you as well?

**Comment by mccare** [comment]
In the end, I had a handler `on('error'...)` and `on('close'...)` and the handler would check if there was an error parameter or the request was aborted. You can see the solution [here](https://github.com/fastify/fastify-multipart/pull/319/commits/0be4c4c604c8f9546704c452b06b657d51df2db7#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R476)
