### ISSUE TITLE
multipart/form-data; boundary=--------------------------770050338242247130429317

### ISSUE THREAD

**Issue by cgonzalezb94** [fastify/fastify-multipart#322]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.1

### Plugin version

5.3.0

### Node.js version

14.17.6

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

The error Unsupported Media Type: multipart/form-data; boundary=-------------------------------------77005033824224713015},"msg":"Unsupported Media Type: multipart/form-data; bou429317, when the implementation is called from the postman.

### Steps to Reproduce
```
import Fastify from 'fastify';
import config from './infra/config';
import { logger, errors } from '@keoworld/gbl-common';
import ramda from 'ramda';
import route from './api/routers';
import multipart from 'fastify-multipart';
import cors from 'fastify-cors';


const exitProcess = () => process.exit(1);

const handleServerError = err => {
  logger.error(err);
  exitProcess();
};

const handleError = async (err, req, res) => {
  const problem = await errors.handler.handle(err);

  res.status(problem.status).send(problem);
};

const handleNotFound = async (req, res) => {
  const err = new errors.AppError(
    errors.ErrorType.NotFound,
    'The requested resource was not found',
    `The resource with url ${req.url} was not found`,
    true
  );
  const problem = await errors.handler.handle(err);

  res.status(problem.status).send(problem);
};

const build = () => {
  const server = Fastify({ logger: true });

  // Add plugins
  server.register(route, { prefix: '/api' });
  server.register(multipart, {
    addToBody: true
  });
  server.register(cors, { origin: '*' });
  server.setErrorHandler(handleError);
  server.setNotFoundHandler(handleNotFound);

  return server;
};

const start = async server => {
  try {
    await server.listen(config.server.port, config.server.ip);
  } catch (err) {
    handleServerError(err);
  }
};

process.on('uncaughtException', errors.handler.handle);
process.on('unhandledRejection', async err => {
  throw err;
});

const run = ramda.pipe(build, start);

run();
```

**Comment by joshdales** [comment]
I think that you are missing a `ContentTypeParser` for `'multipart/form-data'`

```js
server.addContentTypeParser('multipart/form-data', (request, _payload, done) => {
  done(null, request)
})
```

**Comment by Solant** [comment]
I had the same issue using `fastify-multipart` with `fastify-autoload`, when I tried to register `fastify-multipart` for specific folder aka plugin

To make it work, make sure to register `fastify-multipart` **before** any route plugins.

You can also check if multipart is working fine by checking `fastify.hasContentTypeParser('multipart')` for your route plugin instance

**Comment by chenbimo** [comment]
> 

Yes,you are right.very thanks for you.
