### ISSUE TITLE
how to handle error in handler?

### ISSUE THREAD

**Issue by tuananh** [fastify/fastify-multipart#35]
I use the example from readme. how can i handle error in `handler` function, say i want to `reply.code(500).send('error')` for example.

```js

mp.on('error', function(err) {
    // can't catch here ?
})

function handler(field, file, filename, encoding, mimetype) {
        throw new Error('throw')
}
```

**Comment by mcollina** [comment]
can you upload a full example to explain what you want to do? These events are not async functions, so you can't throw safely.

**Comment by tuananh** [comment]
it's pretty much the example in readme, i just add upload function into handler

```js
fastify.get('/', function(req, reply) {
    reply.type('text/html').send(fs.createReadStream(form))
})

fastify.post('/upload', function(req, reply) {
    const mp = req.multipart(handler, function(err) {
        if (err) {
            reply.send(err)
            return
        }

    })

    function handler(field, file, filename, encoding, mimetype) {
        myUploadFunc(file, encoding, mimetype)
            .then(data => {
                // reply.send(...)
            })
            .catch(err => {
                // reply.send(...)
            })
    }
})

fastify.listen(3000, err => {
    if (err) throw err
    log.info(`server listening on ${fastify.server.address().port}`)
})
```

i figure i can catch in handler but the handler is only for 1 file but the form may have multiple files. one of the file upload may fail. how can i catch that and `reply.send(err)` ?

**Comment by mcollina** [comment]
I would just append all those promises to an array and add a `Promise.all()` in the multipart callback.

Anyway, we should really improve promise support here (maybe `req.multipart` should return a promise if a callback is not passed).

**Comment by tuananh** [comment]
Thank you. lemme try that.
