### ISSUE TITLE
Content type parser 'multipart' already present

### ISSUE THREAD

**Issue by SKrind0** [fastify/fastify-multipart#351]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

6.0.0

### Node.js version

17.8.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

21H2

### Description

I'm trying to use multipart to check a schema but when I register it I get an error saying "Content type parser 'multipart' already present"

### Steps to Reproduce

![code](https://user-images.githubusercontent.com/68449193/172524665-6a2807bd-098d-4bb4-ad81-2f728e2aaabb.png)

### Expected Behavior

i want to get this: 
![image](https://user-images.githubusercontent.com/68449193/172524842-06858f57-7981-4346-89fb-61b75573e539.png)

**Comment by climba03003** [comment]
You are using both `fastify-multer` and `@fastify/multipart` together.
They will conflict each another. Please use only one of them.

**Comment by SKrind0** [comment]
> You are using both `fastify-multer` and `@fastify/multipart` together. They will conflict each another. Please use only one of them.

yes, but if I use multer when I want to put the file type in the schema, it gives me an error

![image](https://user-images.githubusercontent.com/68449193/172606993-6fc6a4d9-0e27-48d5-8d57-ef2b082f0804.png)

**Comment by climba03003** [comment]
There is no `type` of `file` in `JSON Schema`.

**Comment by SKrind0** [comment]
> There is no `type` of `file` in `JSON Schema`.

according to swagger it is like that, so how could I do it?

according to swagger it is like this:
![image](https://user-images.githubusercontent.com/68449193/172610467-e9ff77ae-dfe9-47ab-b2ae-21adb9679477.png)

**Comment by climba03003** [comment]
No direct answer. 
If you are using `@fastify/swagger` please create a custom property with `transform`. Then, change it back to the proper type you need.
Or use `OpenAPI 3.0` which is `{ type: "string", format: "binary" }`
