### ISSUE TITLE
hexoid is not a function error upon plugin registration on server start

### ISSUE THREAD

**Issue by SaundersB** [fastify/fastify-multipart#366]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Plugin version

7.1.0

### Node.js version

16.15.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

I'm seeing an error with the hexoid library when I register this plugin with my fastify API:

```
/Users/bsaunders/src/awards/jnrcorp-apis/dist/apps/claims-api/webpack:/jnrcorp-apis/node_modules/@fastify/multipart/index.js:210
  const toID = hexoid()
^
TypeError: hexoid is not a function
    at fastifyMultipart (/Users/bsaunders/src/awards/jnrcorp-apis/dist/apps/claims-api/webpack:/jnrcorp-apis/node_modules/@fastify/multipart/index.js:210:1)
    at Plugin.exec (/Users/bsaunders/src/awards/jnrcorp-apis/dist/apps/claims-api/webpack:/jnrcorp-apis/node_modules/avvio/plugin.js:131:1)
    at Boot.loadPlugin (/Users/bsaunders/src/awards/jnrcorp-apis/dist/apps/claims-api/webpack:/jnrcorp-apis/node_modules/avvio/plugin.js:273:1)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Is there a reason this plugin wouldn't see one of the libraries fastify-multipart declared in the fastify-multipart package.json?

I've made sure I didn't do anything silly like forget to `npm i` in my root project. 

My usage inside a plugin of my own:

```
import FastifyMultipart from '@fastify/multipart';

const fastifyApi = async (
  server,
  opts
) => {
...
server.register(FastifyMultipart);
...
};

export default fp(fastifyApi);
```

which I then register when I run the server with out plugins:

```
const server = Fastify({
    logger: config.fastify,
});
server.register(startServer, config);
try {
    await server.listen(config.server);
  } catch (err) {
    server.log.error(err);
    process.exit(1);
  }
```

### Steps to Reproduce

1. create a new fastify API (v4)
2. register the fastify-multipart plugin
3. start the server
4. see the error above

### Expected Behavior

the API should start without issue and then allow me to accept multipart form content-type. right now my API only accepts application/json as expected via fastify. however, since the API doesn't start I can't use plugin.

**Comment by mcollina** [comment]
I have non idea. My hunch would be to look into the webpack config or stop using webpack altogether.

**Comment by mcollina** [comment]
This is 100% not a problem of this module.

**Comment by simon-tannai** [comment]
@SaundersB I have the same issue with webpack and a former version of `fastify-multipart`. If you didn't found any solution, you have way to solve it:

1. According to [this issue](https://github.com/node-formidable/formidable/issues/337), it seems to be able to fix it by use a Webpack Module. I tried it but it was not working for me (NX environment). If you figure it out with this solution, please comment the thread
2. You can define `@fastify/multipart` as [external dependency](https://webpack.js.org/configuration/externals/). In my NX environments, it looks like this: 
```json
"externalDependencies": [
  "fastify-multipart"
]
```
I suppose in yours it'll be something like:
```javascript
module.exports = {
  //...
  externals: '@fastify/multipart',
};
```

**Comment by Uzlopak** [comment]
@mcollina 

Can I integrate my perf optimized hexoid jit into fastify-multipart?
https://github.com/lukeed/hexoid/pull/2

**Comment by gsimko** [comment]
@mcollina I think the problem is that the way hexoid is imported in this module is incompatible with ES6. The default export of that module can be accessed by require('hexoid').default, and that works fine with webpack/babel.

"according to the ES6 module spec, a default export is no different than a named export with the name default. It is just syntactic sugar which can be statically resolved at compile time"
https://stackoverflow.com/questions/33704714/cant-require-default-export-value-in-babel-6-x

**Comment by gsimko** [comment]
For anyone looking for a quick hacky solution without fixing this module, it's possible from webpack to patch the bad code by adding the following rule:
      ```
{
        test: /@fastify\/multipart/,
        loader: 'string-replace-loader',
        options: {
          search: /const toID = hexoid/,
          replace: 'const toID = hexoid.default',
        }
      }
```

**Comment by mcollina** [comment]
@Uzlopak go ahead with integrating your lib

**Comment by Uzlopak** [comment]
@mcollina 

You have luck, I prepared yesterday something after seeing this issue ;)
