### ISSUE TITLE
When apply { attachFieldsToBody: 'keyValues' }, stringified buffer may not a valid file

### ISSUE THREAD

**Issue by iketiunn** [fastify/fastify-multipart#367]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.1.0

### Plugin version

7.1.0

### Node.js version

v16.14.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3

### Description

In my case, when I apply `{ attachFieldsToBody: 'keyValues' }`, the uploaded image was been stringified from buffer with `buffer.toString()` which is default to uft-8 encoding. And it might not able to be converted correctly back to the buffer.
https://github.com/fastify/fastify-multipart/blob/80d95090006532cf1fa9ac7e0adf1a7ac35cfc06/index.js#L157

Maybe `buffer.toString('binary')` or `buffer.toString('base64')` is more general and acceptable encoding.
If there is no other concern I could make a PR for it.

### Steps to Reproduce

```js
import fastifyMultipart from '@fastify/multipart'
import { writeFile} from 'fs/promises'

app.register(fastifyMultipart, { attachFieldsToBody: 'keyValues' })
app.post('upload', async (req, reply) => {
  const buffer = Buffer.from(req.image)
  await writeFile('path', buffer) // which is not a valid image
  reply.send()
})
```

### Expected Behavior

The written image should be read correctly.

**Comment by climba03003** [comment]
You can check the discussion in https://github.com/fastify/fastify-multipart/pull/348#discussion_r891430786

**Comment by iketiunn** [comment]
Okay, seems like onFile handler could do the trick. Thanks for point it out!
