### ISSUE TITLE
flaky unit tests

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify-multipart#378]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

x

### Plugin version

x

### Node.js version

any

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

The unit tests are flaky and need some attention.

### Steps to Reproduce

see the CI github action

**Comment by cesarvspr** [comment]
@Uzlopak do you know if someone is working on this?
