### ISSUE TITLE
Attaching files to body

### ISSUE THREAD

**Issue by mage1k99** [fastify/fastify-multipart#380]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I wanted to get the fields from the body which is done by setting `attachFieldsToBody` to `keyValues`. this also converts the files into buffer string.

so I need to save this file. It would be better if you gave some idea in documentation regarding saving the file from string buffer as you have given for saving using `pump()`

- I need to figure out the extension of the file that is being sent in request. I could use [file-type](https://www.npmjs.com/package/file-type) but it is a esm only module which messes up the entire project
- If i try to save the buffer I need the extension of the file
- other libraries that find the file type using magic numbers are outdated. so it would be nice if you helped
- I could not use `onFile()` and save the file somewhere using `pump()` because there are multiple types of files I'm going to handle which are organized into folders

**Comment by Eomm** [comment]
> I could use [file-type](https://www.npmjs.com/package/file-type) but it is a esm only module which messes up the entire project

`npm i file-type@16`, it is user x10 times more than the ESM version

> I could not use onFile()

Add some code or I will not be able to help

**Comment by mage1k99** [comment]
Sure.

### Registering the plugin
```ts
export default fp<GlobalOptions>(async (fastify, opts) => {
  fastify.register<FastifyMultipartAttactFieldsToBodyOptions>(
    require("@fastify/multipart"),
    {
      attachFieldsToBody: "keyValues",
    }
  );
  fastify.register<PointOfViewOptions>(
    require("@fastify/view"),
    {
      engine: {
        handlebars: require("handlebars"),
      },
    }
  );
});

```

### A demo route 

```ts
const root: FastifyPluginAsync = async (
  fastify,
  opts
): Promise<void> => {
  fastify.post("/", async function (request, reply) {
    const requestBody = request.body as {
      proof: string | undefined;
      legal_photo: string | undefined;
      proof_name: string | undefined;
      legal_photo_name: string | undefined;
    };
    if (requestBody.proof !== undefined) {
      // the file is received and parsed as string
      console.log("file received!");
     // trying to convert and save
      await createWriteStream(
        `assets/${requestBody.proof_name}`
      ).write(Buffer.from(requestBody.proof));
      console.log(Buffer.from(requestBody.proof));
    }
    return { root: true };
  });
};
```

### What happened ?
I can save the file but the checksums differ. so what I am doing wrong here ?

![image](https://user-images.githubusercontent.com/46259860/184115319-492e08af-a191-4b75-8b51-f99399e2e99f.png)


> npm i file-type@16, it is user x10 times more than the ESM version

Do you mean uses ?

**Comment by mage1k99** [comment]
I figured out a way, converting Buffer string is not helping, so I directly assign buffer as value of the part, which i can access from request body. so I can do things much easier now

```ts
async function onFile(part: any) {
  const buff = await part.toBuffer();
  part.value = buff;
}
```

---

I can't set the type for `part` as `MultipartFile` argument because, the type argument defined in types does not have `value` as property.

![The type defined for `FastifyMultipartAttactFieldsToBodyOptions`](https://user-images.githubusercontent.com/46259860/184129887-0856e6b9-38c8-44fa-9090-6e4a3f1543bd.png)

**Comment by Eomm** [comment]
This could be helpful as well
https://backend.cafe/fastify-multipart-upload

**Comment by mage1k99** [comment]
Yeah that was useful, thanks @Eomm
