### ISSUE TITLE
415 error on routes that does not exist with body multipart/form-data

### ISSUE THREAD

**Issue by mage1k99** [fastify/fastify-multipart#381]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

7.1.0

### Node.js version

v16.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5 (21G72)

### Description

Fastify handles 404 for us, but when used with fastify multipart. it creates an 415 error instead of 404 for routes that does not exist. To demonstrate this I have created a project with fastify cli and tracked the steps to reproduce in each commits [Link to repo](https://github.com/mage1k99/fastify-415-error-demo).

I have tested a bunch of request with different method

| Method | route     | Shows 415 ?             | 
|--------|-----------|-------------------------|
| GET    | /notfound | false, 404 error thrown | 
| POST   | /notfound | true                    | 
| PUT    | /notfound | true                    | 
| PATCH | /notfound | true |
| DELETE | /notfound | true |

As you could see I'm getting 404 for a route that does not exist when using no body in POST request method

![image](https://user-images.githubusercontent.com/46259860/185073644-f124307b-4f41-4c5d-b881-bb5b46a656f0.png)

Now lets change the body type to `multipart/form-data` and send the request

![image](https://user-images.githubusercontent.com/46259860/185073921-fb0bbf87-1f9b-4e12-b6d7-4882ba712db0.png)

This issue is the cause of issue #379 and created new issue as https://github.com/fastify/fastify-multipart/issues/379#issuecomment-1217653444

### Steps to Reproduce

- create a project with fastify cli
- add the `@fastify/multipart` plugin
- register the multipart plugin by copy pasting the below code
```ts
import { FastifyMultipartAttactFieldsToBodyOptions } from "@fastify/multipart";
import fp from "fastify-plugin";

export interface RootPluginOptions {
  // Specify Support plugin options here
}

// The use of fastify-plugin is required to be able
// to export the decorators to the outer scope
export default fp<RootPluginOptions>(async (fastify, opts) => {
  fastify.register<FastifyMultipartAttactFieldsToBodyOptions>(
    require("@fastify/multipart"),
    {
      attachFieldsToBody: true,
    }
  );
});
```
- create route that accepts multipart/form-data in request
- send POST request with `multipart/form-data` as body to any route that does not exist. In our case I used `/notfound` route.
- the error is shown

### Expected Behavior

- Throw 404 error instead of 415 error when a `POST`, `PUT`, `PATCH`,` DELETE` route that does not exist.
- This also creates confusion when development phase as the developer might get confused if the plugin got registred or not instead of checking the url

**Comment by mcollina** [comment]
Good spot! We should basically skip all the incoming body if it's a 404 request. This can be done by adding a few if checks in fastify-multipart using the `req.is404` property (https://www.fastify.io/docs/latest/Reference/Request/).

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mage1k99** [comment]
Sorry about the delay, the email notification did not work. will look at it as soon as possible

**Comment by mage1k99** [comment]
Hey @mcollina I don't think that this is the issue with fastify-multipart, this is issue with  Should this be done in fastify itself ? This is because unregistered content type can cause 415 so checking if the route exist before checking the content type is registered is a good idea

![image](https://user-images.githubusercontent.com/46259860/190850527-85035a6b-ce3c-4c3a-af77-dfeadf9f21bb.png)

As you could see at that 404 routes are handled by the default handler in `onRequest` 

so adding `request.is404` in `ContentTypeParser.js` [Right here](https://github.com/fastify/fastify/blob/e9838a23caa87928e4719c5125f103709cbb537c/lib/contentTypeParser.js#L148) should do the job right ?

![image](https://user-images.githubusercontent.com/46259860/190850991-c4b9c10d-046c-446c-a00b-d5ebb1140b2c.png)

**Comment by mage1k99** [comment]
I have made a pull request, https://github.com/fastify/fastify/pull/4286

**Comment by mcollina** [comment]
Good spot, thanks!
