### ISSUE TITLE
Why dont you give us request object to onFile() callback?

### ISSUE THREAD

**Issue by init-database** [fastify/fastify-multipart#382]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

currently you are giving us `part` of `req.parts`

```
{
     attachFieldsToBody: 'keyValues',
     onFile: async (part) => {
            // we only have part here
            // what if we want to do something else with request?
     },
}
```

why don't you pass the request object instead? so that we can perform request.saveRequestFiles()

### Motivation

so that we can perform request.saveRequestFiles()

**Comment by Uzlopak** [comment]
It doesnt make sense to me to call saveRequestFiles in the onFile.handler.

**Comment by init-database** [comment]
it does to me,

The current possible option are first: to buffer in memory which the docs it self is always warn us about it and the second option is to save the file to disk using pump() while the others text fields haven't run through schema validation yet, what if some fields got validation error? you have to remove the file that you have saved before manually. and what if the file you have saved already overwrite old file? does this make sense to you?
