### ISSUE TITLE
`RequestFileTooLargeError` is not raised with streams even though `fileSize` limit is set

### ISSUE THREAD

**Issue by svsool** [fastify/fastify-multipart#383]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.4.0

### Plugin version

7.1.0

### Node.js version

18.0.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3

### Description

Thanks for this plugin.

I use `@fastify/multipart` for image upload and noticed that `RequestFileTooLargeError` is not raised with file streams in production env.

Here is [the test](https://github.com/fastify/fastify-multipart/blob/master/test/multipart-fileLimit.test.js#L12) in the current codebase that supposed to test that this error raised and it's raised with in-memory random buffer not bound to disk IO delays.

Although if one replaces `randomFileBuffer` with real stream `fs.createReadStream('/tmp/images/15mb.jpeg')` bigger than `fileSize` test starts to fail, but it expected to pass.

![image](https://user-images.githubusercontent.com/1452141/186844205-c1f06e3b-d4bc-4ebb-a970-be2779b7665c.png)

![image](https://user-images.githubusercontent.com/1452141/186844425-8a75f216-7a19-42fb-9db7-41ee795de742.png)

It's not obvious to me why error is not propagated in this case or should it at all.

### Steps to Reproduce

Replace `randomFileBuffer` with `fs.createReadStream('/tmp/images/15mb.jpeg')` in [this test](https://github.com/fastify/fastify-multipart/blob/master/test/multipart-fileLimit.test.js#L12).

### Expected Behavior

I expect that `RequestFileTooLargeError` would be raised when read stream supplied.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
