### ISSUE TITLE
Unsupported Media Type: multipart/form-data; boundary=--------------------------081092531767619493751707

### ISSUE THREAD

**Issue by aymensbh** [fastify/fastify-multipart#395]
import multipart from "@fastify/multipart";
server.register(multipart, {
  limits: {
    fieldNameSize: 100, // Max field name size in bytes
    fieldSize: 100, // Max field value size in bytes
    fields: 10, // Max number of non-file fields
    fileSize: 1000000, // For multipart forms, the max file size in bytes
    files: 1, // Max number of file fields
    headerPairs: 2000, // Max number of header key=>value pairs
  },
  attachFieldsToBody: true,
});

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by aymensbh** [comment]
```
import multipart from "@fastify/multipart";
import formBodyPlugin from "@fastify/formbody";
import fastify from "fastify";

const server = fastify({ logger: true, trustProxy: true });

server.register(multipart, {
  limits: {
    fieldNameSize: 100,
    fieldSize: 100,
    fields: 10,
    fileSize: 1000000,
    files: 1,
    headerPairs: 2000,
  },
  attachFieldsToBody: true,
});

server.register(formBodyPlugin);

fastify.post("/", async function (req, reply) {
  const data = await req.file();
  reply.send({ fileName: data.filename });
});

server.listen(
  {
    port: (process.env.PORT as any) || 8080,
    host: (process.env.HOST as any) || "0.0.0.0",
  },
  (err, address) => {
    if (err) {
      console.error(err);
      process.exit(1);
    }
  }
);
```

**Comment by aymensbh** [comment]
```
//Error
{
    "statusCode": 415,
    "code": "FST_ERR_CTP_INVALID_MEDIA_TYPE",
    "error": "Unsupported Media Type",
    "message": "Unsupported Media Type: multipart/form-data; boundary=--------------------------848693729628644525322511"
}

```

**Comment by aymensbh** [comment]
![Screen Shot 2022-10-23 at 12 00 05 PM](https://user-images.githubusercontent.com/49540075/197388365-e36244f5-2447-4096-b945-5d21a17fa649.png)

**Comment by aymensbh** [comment]
Never mind, I just needed to register the multipart plugin in the right order, now it works.
