### ISSUE TITLE
Error: Multipart: Boundary not found

### ISSUE THREAD

**Issue by DiogoMarques2003** [fastify/fastify-multipart#399]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^4.10.2

### Plugin version

^7.3.0

### Node.js version

16.16.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Linux 5.15.0-56-generic on x86_64

### Description

When i trie send the request from postman this works, but when i send using axios in react native i get this error.

### Steps to Reproduce

backend:
```js
const files = await req.saveRequestFiles(); // error on this line

    if (!files || files.length === 0) throw new AppError('Tens de enviar um PDF', 400);

    const file = files[0];

    if (file.mimetype !== 'application/pdf' || file.filename.split('.').at(-1) !== 'pdf') throw new AppError('Tens de enviar um PDF', 400);

    if (!file.filepath) throw new AppError('Erro ao enviar o ficheiro', 500);

    req.pdfFilePath = file.filepath;
```
make the request with axios
```js
const data = new FormData();
data.append('', curriculum)
console.log(data); //{"_parts": [["", [Object]]]}
const response = await api.put("/user/change/curriculum", JSON.stringify(data), {
    headers: {
        'Content-Type': `multipart/form-data`
    }
});
```

**Comment by DiogoMarques2003** [comment]
> data.append, why is the first parameter an empty string?

I already try pass one name but this return the same erorr.
On postman this data.append the first parameter is a empty string

**Comment by Uzlopak** [comment]
You are using axios wrong.

You dont have to put formdata through JSON.stringify but assigning the formdata Instance directly to the request body. Then axios will serialize it properly.

https://stackoverflow.com/questions/47630163/axios-post-request-to-send-form-data

**Comment by DiogoMarques2003** [comment]
![image](https://user-images.githubusercontent.com/52538977/205686733-8a1764b6-0bd4-4e41-b1bf-ce850f892f4f.png)
With this i get the same error

**Comment by DiogoMarques2003** [comment]
![image](https://user-images.githubusercontent.com/52538977/205687375-927a32a3-3aa4-4f48-9560-2cb0fc3d3744.png)
@Uzlopak

**Comment by DiogoMarques2003** [comment]
> Network Error in axios means that the client cant connect to the server on tcp/ip level. Check if your service runs.

Yup is running and if i leave the JSON.stringfy this works fine

**Comment by Uzlopak** [comment]
I would try not to set the content type header manually. Axios sets it imho itself.

Well i cant test it, i am with my wife in the mall. also this is not a @fastify/multipart issue per se but a axios issue. I would recommend to check the axios documentation.

**Comment by DiogoMarques2003** [comment]
Ok thanks man
