### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by arthurfiorette** [fastify/fastify-multipart#417]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^4

### Plugin version

^7

### Node.js version

v16.14.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

WSL

### Description

When using `saveRequestFiles` within a `Content-Type: multipart/form-data` without any content on body it throws `Cannot convert undefined or null to object` [here](https://github.com/fastify/fastify-multipart/blob/1a0c683cf5880db9b36173a43c504c2b90a96662/index.js#L552). Because [here](https://github.com/fastify/fastify-multipart/blob/1a0c683cf5880db9b36173a43c504c2b90a96662/index.js#L527) we don't assure the body has actually something.

### Steps to Reproduce

Send this request to an simple route that calls `saveRequestFiles()` alongside with `attachFieldsToBody: true`.
 
 ```http
POST /test HTTP/1.1
Content-Type: multipart/form-data; boundary=BOUNDARY
Accept: */*

--BOUNDARY--
 ```

### Expected Behavior

I'd love to send a PR to fix this case but I don't know exactly what behavior it should do...
Should it return `[]` directly? Should I throw an empty body error?

**Comment by arthurfiorette** [comment]
@Uzlopak just the request.

**Comment by Eomm** [comment]
Thanks for reporting!
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by arthurfiorette** [comment]
Should it return [] directly? Should I throw an empty body error?
