### ISSUE TITLE
When using `request.parts()` the iterators keeps hanging until file stream is consumed

### ISSUE THREAD

**Issue by JacopoPatroclo** [fastify/fastify-multipart#418]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi,
first of all thanks for the amazing work that you all do.
Then on the issue/question at hand, I've created a small repo to reproduce it [here](https://github.com/JacopoPatroclo/fastify-multipart-parts-iterator-hangs-example).

Basically the expected behaviour is when all the parts of the request are parsed the parts async iterator will end ignoring the fact that the file stream has been consumed.

I'm not sure if this is a bug or it's expected to work like this, I've just find out this odd (in my opinion) behavior.

Hope the example is clear enough to make up for my poor english skills.

Thanks again.

**Comment by climba03003** [comment]
You must consume the file before the `next` part is allowed to consume.
Even if it is an `async iterator`, the backbone is consuming the `multipart` stream.
There is no way to skip consuming the file and reach the next block of field.
