### ISSUE TITLE
multipart data objects in array don't converting, still string

### ISSUE THREAD

**Issue by orcuntuna** [fastify/fastify-multipart#429]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.14.1

### Plugin version

7.5.0

### Node.js version

18.12.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3.1

### Description

When I want to send an array of objects in formdata, it keeps the keys as strings and adds all the records to the body one by one.

**fastify plugin config:**
![image](https://user-images.githubusercontent.com/22179849/229120031-3880128d-8f7a-419f-81f9-b67af7c81b8d.png)

I tried only addToBody config, only attachFieldsToBody and attachFieldsToBody=keyValues
I tried without await

**postman request:**
![image](https://user-images.githubusercontent.com/22179849/229119755-7a57940e-7bdd-4e08-925f-4db720921be2.png)

**request.body log:**
![image](https://user-images.githubusercontent.com/22179849/229120345-21a036af-703c-4834-9fe1-fddb4e4b3e47.png)

### Steps to Reproduce

```js
await server.register(fastifyMultipart, {
    addToBody: true,
    attachFieldsToBody: true,
})
```

### Expected Behavior

**expected result:** 
```json
{
  "users": [
    {
      "name": "Jhon",
      "surname": "Wick"
    },
    {
      "name": "Jeff",
      "surname": "Bezos"
    }
  ]
}

```

**Comment by arthurfiorette** [comment]
It seems that your problem is related to other pieces of code in you server, can you build up a small reproducible example?

**Comment by mcollina** [comment]
I don't think this is supported at all.


Would you like to send a Pull Request to address this issue? Remember to add unit tests.
