### ISSUE TITLE
How can I count the number of files in the same request?

### ISSUE THREAD

**Issue by Uriel29** [fastify/fastify-multipart#432]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi!!

"How can I count the number of files in the same request? I am sending the files via XMLHttpRequest, and I tried it this way:"

case 2 files create a new folder

```javascript
fastify.post('/', async function (req, reply) {
  const parts = req.files()
 let cont = 0
  for await (const part of parts) {
count ++
    await pump(part.file, fs.createWriteStream(part.filename))
  }
  reply.send(count)
})
// 1
```

hugs

**Comment by khokm** [comment]
Hello!
Why are you not satisfied with your current solution?
If you don't want to save files on disk, then, instead of
```js
 await pump(part.file, fs.createWriteStream(part.filename))
```
use
```js
 await part.toBuffer()
```
If you don't want to save it to memory either, use:
```js
part.file.on("data", () => {});
```

**Comment by Uriel29** [comment]
I understood the problem, I was making a request with xmlhttprequest.
And in my code, I send one file at a time!
That means in the fastify request, there is only one file correctly!
