### ISSUE TITLE
onFile hook doesn't work on files array field with (attachFieldsToBody: "keyValues")

### ISSUE THREAD

**Issue by alifuma92** [fastify/fastify-multipart#447]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Plugin version

7.6.0

### Node.js version

18.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.2 (Ventura)

### Description

I want to attach files to my body which also contains other data like strings and booleans.

I used the **attachFieldsToBody: "keyValues"** option, and it seems to work.

**There are however two problems:**

1) the file is attached to the body with the default value buffer.toString(). Here it doesn't appear to convert to a base64 or utf-8 string due to the presence of unknown characters. So it's impossible to restore the buffer and therefore the file from that string. I managed to get around this by using the **onFile hook** which allowed me to return a correct base64 string.

```
onFile: async function (part) {
  const buff = await part.toBuffer();
  const base64_file = buff.toString("base64");
  const type = await fileTypeFromBuffer(buff);
  part.value = {
      file: base64_file,
      type: type,
  };
}
```

2) The problem now is that if I pass more than one file into the same form field, I get returned an array of strings that are not "processed" by the "onFile" hook and are therefore unusable. it's like the onFile hook only works if there is a single file in a specific key of the body, if it's an array it doesn't get executed.

Can anyone come and help me?

### Steps to Reproduce

**1) package.json**

```
{
  "name": "fastifyplayground",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@fastify/multipart": "^7.6.0",
    "fastify": "^4.17.0",
    "file-type": "^18.5.0",
    "mime-types": "^2.1.35"
  },
  "type": "module"
}
```

**2) index.js**

```
import Fastify from "fastify";
import { fileTypeFromBuffer } from "file-type";

// Require the framework and instantiate it
const fastify = Fastify({
    logger: true,
});

// register multipart plugin
fastify.register(import("@fastify/multipart"), {
    attachFieldsToBody: "keyValues",
    limits: {
        fileSize: 1048576, // 1MB
    },
    onFile: async function (part) {
        const buff = await part.toBuffer();
        const base64_file = buff.toString("base64");
        const type = await fileTypeFromBuffer(buff);
        part.value = {
            file: base64_file,
            type: type,
        };
    },
});

// Declare a route
fastify.route({
    method: "POST",
    url: "/upload",
    handler: async (request, reply) => {
        // get body values
        const test = request.body.test;
        const image = request.body.image;

        // response
        return {
            test: test,
            image: image,
        };
    },
});

// Run the server!
const start = async () => {
    try {
        await fastify.listen({ port: 3000 });
    } catch (err) {
        fastify.log.error(err);
        process.exit(1);
    }
};
start();

```

**Comment by mcollina** [comment]
Can you please ad a node.js script to reproduce the problem?

**Comment by alifuma92** [comment]
I used postman to do the api call 

Here when i upload a single file

<img width="821" alt="Screenshot 2023-06-13 alle 10 19 15" src="https://github.com/fastify/fastify-multipart/assets/44839296/77dc0baf-847b-48c7-85b1-442f651b06ab">

Here when i upload 2 files
<img width="821" alt="Screenshot 2023-06-13 alle 10 18 45" src="https://github.com/fastify/fastify-multipart/assets/44839296/9125e487-bdc3-4cf0-adf0-88e8497ee06d">

**Comment by mcollina** [comment]
I figured out as much, that's why I asked if you could add a node.js script to reproduce the problem.

**Comment by alifuma92** [comment]
I try to generate nodejs native script from postman 
```
var https = require('follow-redirects').https;
var fs = require('fs');

var options = {
  'method': 'POST',
  'hostname': 'localhost',
  'port': 3000,
  'path': '/upload',
  'headers': {
  },
  'maxRedirects': 20
};

var req = https.request(options, function (res) {
  var chunks = [];

  res.on("data", function (chunk) {
    chunks.push(chunk);
  });

  res.on("end", function (chunk) {
    var body = Buffer.concat(chunks);
    console.log(body.toString());
  });

  res.on("error", function (error) {
    console.error(error);
  });
});

var postData = "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"test\"\r\n\r\nhello world\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"image\"; filename=\"Attività - con iscrizioni_d.png\"\r\nContent-Type: \"{Insert_File_Content_Type}\"\r\n\r\n" + fs.readFileSync('{FILE_PATH}') + "\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--";

req.setHeader('content-type', 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW');

req.write(postData);

req.end();
```

**Comment by alifuma92** [comment]
Checking the source code of the @fastify/multipart, i noticed that at line 166 of the file 
**_"node_modules/@fastify/multipart/index.js"_**

in that file there is this portion of code at line 166

```
if (options.attachFieldsToBody === 'keyValues') {
        const body = {}
        for (const key of Object.keys(req.body)) {
          const field = req.body[key]
          if (field.value !== undefined) {
            body[key] = field.value
          } else if (Array.isArray(field)) {
            body[key] = field.map(item => {
              if (item._buf !== undefined) {
                return item._buf.toString()
              }
              return item.value
            })
          } else if (field._buf !== undefined) {
            body[key] = field._buf.toString()
          }
        }
        req.body = body
      }
```

As you can see, a file buffer is "toString()" (which however generates a malformed string), it would be enough to set the "toString('base64')" encoding to solve the problem.

I tried to manually edit the file in question of the package and it works fine without even having to use the "onFile" hook.

i Write here how I changed the code of the file.

```
if (options.attachFieldsToBody === 'keyValues') {
        const body = {}
        for (const key of Object.keys(req.body)) {
          const field = req.body[key]
          if (field.value !== undefined) {
            body[key] = field.value
          } else if (Array.isArray(field)) {
            body[key] = field.map(item => {
              if (item._buf !== undefined) {
                return item._buf.toString("base64")
              }
              return item.value
            })
          } else if (field._buf !== undefined) {
            body[key] = field._buf.toString("base64")
          }
        }
        req.body = body
      }
```


is it possible to release an update of the so that this change is present?

In this way file management would be immediate and very easy :)

**Comment by mcollina** [comment]
I don't think converting things to `base64` is the correct solution here. More likely we should avoid calling `toString()` completely and leave them as buffers.

Unfortunately I don't have the time to look into this right now. A pull request to fix it would be appreciated.

**Comment by alifuma92** [comment]
In fact it's the best solution, i just created the pull request.
https://github.com/fastify/fastify-multipart/pull/456

I hope it is approved soon :)

Thank you!@mcollina !! 👍

**Comment by johanbook** [comment]
I have some issues with this as well where I want to access the buffers for an array of files. It seems it has been remedied in https://github.com/fastify/fastify-multipart/pull/468. Is there any plan for when this will be released?

**Comment by savvykir** [comment]
Any updates in here?

**Comment by savvykir** [comment]
@mcollina Could you help in here? I have the same issue. Could you release it?
