### ISSUE TITLE
FastifyRequest interface is redeclared instead of augmented

### ISSUE THREAD

**Issue by zaventh** [fastify/fastify-multipart#457]
When augmenting the types in a module, the underlying module needs to be imported. Otherwise TypeScript replaces the underlying type information with only what is being declared:

https://github.com/fastify/fastify-multipart/blob/c61b23ea044c0b9207951b606d162ab4824ecb83/index.d.ts#L1-L8

The module `fastify` needs to be imported in this file for the module to be augmented instead of replaced. Trivial example:

```ts
// without the below line, the entire FastifyRequest type will only have foo defined in this context
import 'fastify';

declare module 'fastify' {
  export interface FastifyRequest {
    foo?: any;
  }
}

```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by climba03003** [comment]
Not really the case, `fastify` should always be imported inside any `fastify` project.
It must not be imported inside any plugin with only `import 'fastify';`.

I would like to see a reproducible project and check why / which setup requires such change.
Note that I never use `fastify-cli`, if it is `fastify-cli` related issue the simple fix should be always include the `fastify` types inside `tsconfig`.

**Comment by gurgunday** [comment]
I really don’t see the problem as we always do it this way, see fastify-cookie and others

Because there was no response to climba’s demand, I will close this issue, but feel free to comment with a reproducible example that demonstrates the need for such a change

Thanks for your understanding
