### ISSUE TITLE
File size setting not working on production

### ISSUE THREAD

**Issue by fdbatista** [fastify/fastify-multipart#460]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello.

I cannot send files heavier than 1 MB on production, so I tried to set a bigger fileSize and a fieldSize too, with no luck.
This is how I am registering the multipart plugin:

```
const registerMultipart = (fastify) => {
    fastify.register(require('@fastify/multipart'), {
        limits: {
            fileSize: 30000000,
            fieldSize: 30000000,
            fieldNameSize: 3000000,
            headerSize: 30000000,
        }
    })
}
```

The weird thing is that everything works on my localhost. But on production, if I try to upload a 2 MB file, I get an error.
Not a filesize error, but a CORS error, which doesn't happen with smaller-than-1-MB files.

Any clues?
These are my Fastify dependencies and versions:

```
"dependencies": {
    "@fastify/autoload": "^5.7.1",
    "@fastify/cors": "^8.2.0",
    "@fastify/jwt": "^7.0.0",
    "@fastify/multipart": "^7.6.0",
    "@fastify/rate-limit": "^8.0.1",
    "@fastify/swagger": "^8.8.0",
    "@fastify/swagger-ui": "^1.9.2",
    "fastify": "^4.10.2",
    "fastify-plugin": "^4.5.0",
  },
```

**Comment by mcollina** [comment]
What error do you get? Where are you deploying your code?

**Comment by gurgunday** [comment]
Hey,

We will need more information than that, it's usually a restriction of your hosting provider, especially if it's serverless

I will be closing the issue for inactivity, but feel free to comment with more information and we can reopen it
