### ISSUE TITLE
Schema validation breaks when attachFieldsToBody is set to 'keyValues'

### ISSUE THREAD

**Issue by smaspe** [fastify/fastify-multipart#489]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

7.7.3

### Stopped working in version

8.0.0

### Node.js version

18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.6

### 💥 Regression Report

When setting `{attachFieldsToBody: 'keyValues'}`, the content of the file is attached to the body, using the name of the field.

According to the documentation here: https://github.com/fastify/fastify-multipart#json-schema-body-validation, we'd expect a string.

However, since version 8.0.0 (specifically, this particular change here: https://github.com/fastify/fastify-multipart/commit/c195d5f97d98d3b543b3d36fb82ffc03ec802646#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L176, the object is attached as a Buffer.

Using JSON Schema, as far as I know, it is not possible to represent a Buffer object.

### Steps to Reproduce

- Install version 8.0.0
- Try to define a body schema that validates a buffer?

Here is a short example of a server:
```ts
import fastifyMultipart from "@fastify/multipart";
import fastify from "fastify";

const app = fastify({ ignoreTrailingSlash: true });
app.register(fastifyMultipart, {
  attachFieldsToBody: "keyValues",
});

app.post(
  "/test",
  {
    schema: {
      body: {
        type: "object",
        properties: {
          myFile: { type: "string" },
        },
      },
    },
  },
  async (request, reply) => {
    reply.send();
  }
);

app.listen({ port: 3000 });
```

It works fine in 7.7.3. With 8.0.0, `myFile` is now a Buffer, and this server returns this:

```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "body/myFile must be string"
}
```

### Expected Behavior

- `body.myFile` should be a string, or there is a documented clear way of defining a Buffer in the JSON Schema validation

**Comment by gurgunday** [comment]
Good spot, the docs shouldn’t say that

**Comment by gurgunday** [comment]
You can use the `object` type for buffers
