### ISSUE TITLE
Incorrect behavior of per-request limits

### ISSUE THREAD

**Issue by hash0000** [fastify/fastify-multipart#496]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

8.0.0

### Node.js version

21.2.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

W11. 23H2 (22631.2715)

### Description

Clear and concise:
1. Inaccuracy in documentation (possibly);
2. Inability to specify limits for each route separately.

I also want to clarify that I am using TypeScript.
TypeScript version: 5.3.2.

### Steps to Reproduce

1. From plugin types: 
![image](https://github.com/fastify/fastify-multipart/assets/65348391/9de0be13-bfcc-4a65-9f81-46821ade8e1e)
In `BusboyConfig` interface simply no `throwFileSizeLimit`.

2. Set limits for `request.files()`
![image](https://github.com/fastify/fastify-multipart/assets/65348391/191dc3a2-392a-4431-b352-20bb681539a0)
Set `throwFileSizeLimit: true` globally
![image](https://github.com/fastify/fastify-multipart/assets/65348391/75d0ad42-01a5-45f0-bad4-71984987547a)

Send larger files and in larger quantities. As a result, we do NOT get exception.
However, If you specify the same parameters globally or for the `saveRequestFiles` function, the limits will work correctly.

### Expected Behavior

1. The first thing I would like to say is that the instructions in the documentation are incorrect (or am I wrong?).
Example from docs:
![image](https://github.com/fastify/fastify-multipart/assets/65348391/a05ddf5d-70ba-4fee-82b4-c3c1c157b83d)
However, I cannot specify such a parameter due to differences in types. `files()` allow `BusboyConfig` interface, in which there is no `throwFileSizeLimit` parameter. It is only available in the `FastifyMultipartBaseOptions` interface.
![image](https://github.com/fastify/fastify-multipart/assets/65348391/c5de6f81-0f6a-492c-9b35-b71ebe264ece)

2. What I'm trying to do: set basic global limits when registering a plugin and specify the limits of each route separately, for part of them, as an overwrite of the global ones.
Global:
```ts
 const fastifyMultipartOptions: FastifyMultipartOptions = {
    limits: {
      fieldNameSize: 100,
      fieldSize: 100,
      fields: 5,
      fileSize: 1,
      headerPairs: 2000,
      files: 5,
    },
    throwFileSizeLimit: true,
  };
  await app.register(fastifyMultipart, fastifyMultipartOptions);
```
For route (I can't set `throwFileSizeLimit` because of the problem described earlier):
`await request.files({ limits: { files: 1, fileSize: 1 } });`

The limits specified globally work correctly, but the specified limits for a request are completely ignored.
I tried this way: use `saveRequestFiles(opts)`, where setting limits works correctly, however, I cannot get `toBuffer()` from the `savedRequestFiles` array, which makes this function not relevant for me.

**Comment by iamarthurk** [comment]
+1

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

(Alternatively a PR with a proposed change would also be fine).

**Comment by hash0000** [comment]
@mcollina, I think I figured out the incorrect validation of limits.
I tested again and found a correlation with whether I call `file.toBuffer()` or not. If `file.toBuffer()` is not called after receiving a file stream, then the limits are ignored. I wrote a test [application](https://github.com/hash0000/fastify-multipart-example) where you can see what I mean.

**Comment by mcollina** [comment]
The limits are enforced when the file is consumed (when the data is read from the underlying socket).
