### ISSUE TITLE
await req.file returns undefined

### ISSUE THREAD

**Issue by LMS5413** [fastify/fastify-multipart#498]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

8.0.0

### Node.js version

Bun sh (1.0.15+b3bdf22eb)

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

Im trying using the method `await req.file()` but is dosen`t work,

### Steps to Reproduce

Register the plugin
use <Fastify>.route

### Expected Behavior

Appears req.file() object.

**Comment by gurgunday** [comment]
Hmm, haven't seen that node version before ;)

I don't have Bun installed and it might take a while before I do that

FYI, we don't officially support Bun

**Comment by climba03003** [comment]
Closing as it beyond our support (bun related).

**Comment by tousifhabib** [comment]
@climba03003 can we please get this fix in the upstream? Also using bun.

Would appreciate it very much, thanks

https://github.com/oven-sh/bun/issues/5265

**Comment by Uzlopak** [comment]
@tousifhabib 

Everybody talking about upstreaming the workaround, but nobody is opening a PR in @fastify/busboy...

**Comment by alexmacarthur** [comment]
I'm also seeing this issue.
