### ISSUE TITLE
Issue v5 release

### ISSUE THREAD

**Issue by gurgunday** [fastify/fastify-multipart#511]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

`next` branch is ready for Fastify v5 release, it currently tracks just ahead of the `main` branch

**Comment by mcollina** [comment]
Please don't open issue for releasing the "fastify v5 release". It would mean we have 60+ issues to clear right now, and close when we ship. In previous majors, we have prepared a single issue with a long TODO list.

**Comment by jsumners** [comment]
@mcollina please review https://github.com/orgs/fastify/discussions/39. This issue is for tracking in the "Ready to release" column of https://github.com/orgs/fastify/projects/8, aka the todo list.
