### ISSUE TITLE
上传大文件时，经常会挂起，前端得不到响应

### ISSUE THREAD

**Issue by wintsa123** [fastify/fastify-multipart#513]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

10.3.0

### Plugin version

8.1.0

### Node.js version

20

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

2024.3.7

### Description

Front-end zip packet response hangs after sending request，but pdf、png Normal operation。

### Steps to Reproduce

![企业微信截图_17097984385950](https://github.com/fastify/fastify-multipart/assets/47288630/6dcf8159-420d-41bf-ae40-f2c086b2fc1c)
![image](https://github.com/fastify/fastify-multipart/assets/47288630/3b05a539-e69e-4afe-8d57-c9e41160ac42)
it work，but sometime cant response，example upload zip file。

### Expected Behavior

work！！！！！

**Comment by Uzlopak** [comment]
@climba03003 do you understand what OP wrote in chinese?

**Comment by wintsa123** [comment]
![image](https://github.com/fastify/fastify-multipart/assets/47288630/453f74b4-1f88-4edb-833f-f0347be8bdc5)
@Uzlopak i use nest10 ，The backend successfully parses the file, but the frontend often does not receive a response

**Comment by climba03003** [comment]
> do you understand what OP wrote in chinese?

When uploading large file, it often hangs and doesn't response.

>  it work，but sometime cant response，example upload zip file。

I recommend to provide a reproducible code example that is isolated to `fastify`.
That means it should not contain `Nest 10`.

**Comment by wintsa123** [comment]
> > 你明白OP用中文写的东西吗？
> 
> 上传大文件时，它经常挂起并且没有响应。
> 
> > 它有效，但有时无法响应，例如上传zip文件。
> 
> 我建议提供一个可重现的代码示例，该代码示例与 .这意味着它不应包含 .`fastify``Nest 10`

我是在nest10的fastify 适配器上使用的fastify-multipart，我检查过只要使用了req.file()就不会有响应到前端，不管文件大小，有时可以有时不行，但我确定只要使用了await req.file()就会导致这个问题

**Comment by climba03003** [comment]
> > > 你明白OP用中文写的东西吗？
> > 
> > 
> > 上传大文件时，它经常挂起并且没有响应。
> > > 它有效，但有时无法响应，例如上传zip文件。
> > 
> > 
> > 我建议提供一个可重现的代码示例，该代码示例与 .这意味着它不应包含 .`` fastify``Nest 10 ``
> 
> 我是在nest10的fastify 适配器上使用的fastify-multipart，我检查过只要使用了req.file()就不会有响应到前端，不管文件大小，有时可以有时不行，但我确定只要使用了await req.file()就会导致这个问题

If it is the case, and you are using the same code as you shown.
Please don't forget to consume the stream.

For example, you may try to `buffer` it and see if it helps.

```js
const file = request.file()
await file.toBuffer()
```

**Comment by wintsa123** [comment]
> > > > 你明白OP用中文写的东西吗？
> > > 
> > > 
> > > 上传大文件时，它经常挂起并且没有响应。
> > > > 它有效，但有时无法响应，例如上传zip文件。
> > > 
> > > 
> > > 我建议提供一个可重现的代码示例，该代码示例与 .这意味着它不应包含 .巢 10 ''` fastify`
> > 
> > 
> > 我是在nest10的fastify 适配器上使用的fastify-multipart，我检查过只要使用了req.file（）就不会有响应到前端，不管文件大小，有时可以有时不行，但我确定只要使用了await req.file（）就会导致这个问题
> 
> 如果是这种情况，并且您使用的代码与所示代码相同。请不要忘记使用流。
> 
> 例如，您可以尝试一下，看看是否有帮助。`buffer`
> 
> ```js
> const file = await request.file()
> await file.toBuffer()
> ```

crazy！！！it working！I've been trying all afternoon to troubleshoot various middleware issues
![image](https://github.com/fastify/fastify-multipart/assets/47288630/68666d62-c75a-4f58-ab73-d9b6cbe11e5b)

**Comment by wintsa123** [comment]
```javascripts
const file = await request.file()
await file.toBuffer()
```
Why is it not included in the API!

**Comment by wintsa123** [comment]
> 
> ```js
> const file = await request.file()
> await file.toBuffer()
> ```

 stack: 'FastifyError: request file too large\n' +
      '    at Object.toBuffer (D:\nestjs-mysql-api-master\node_modules\@fastify\multipart\index.js:330:21)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at TmpRedisService.pdfToExcel (D:\nestjs-mysql-api-master\src\api\tmp-redis\tmp-redis.service.ts:106:13)\n' +
      '    at TmpRedisController.pdfToExcel (D:\nestjs-mysql-api-master\src\api\tmp-redis\tmp-redis.controller.ts:51:18
      
```js
  app.register(fastifyMultipart, {
    limits: {
      fileSize: 100 * 1024 * 1024, // 设置上传文件的最大大小，单位为字节，这里设置为 100MB
    },
  });
```
i try to change limmit，but it cant work

**Comment by climba03003** [comment]
> Why is it not included in the API!

It told you in the example. You probably need to write it to a file, not buffered in memory.
I am telling you to buffer it only because I want to test if you missed to consume the stream.

![image](https://github.com/fastify/fastify-multipart/assets/23028015/b5b536d0-14b2-4c03-8d61-349e19add56b)
