### ISSUE TITLE
Streaming to Pinata IPFS via pinata-web3 sdk

### ISSUE THREAD

**Issue by truongly1997** [fastify/fastify-multipart#560]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I have 2 cases need to upload file to S3 and also to IPFS by using [pinata-web3](https://docs.pinata.cloud/web3/sdk/upload/stream).

but in document I saw they support [stream](https://docs.pinata.cloud/web3/sdk/upload/stream#usage) function but I have try but it still not working. I don't know what is difference even I using Readable.from to make it as Readable ?

```typescript

import { Injectable } from '@nestjs/common'
import { Readable } from 'stream'

import { PinataSDK } from 'pinata-web3'
import { ConfigService } from '@nestjs/config'
import { MultipartFile } from '@fastify/multipart'
import { createReadStream } from 'fs'

@Injectable()
export class PublicService {
  private readonly pinata: PinataSDK

  constructor(private readonly config: ConfigService) {
    this.pinata = new PinataSDK({
      pinataJwt: this.config.get<string>('pinata.jwt'),
      pinataGateway: this.config.get<string>('pinata.url'),
    })
  }

  async uploadToIPFS(file: MultipartFile) {
    try {
      // NOT WOKRING
      const response = await this.pinata.upload.stream(Readable.from(file.file, {}))
      const response = await this.pinata.upload.stream(file.file)
      console.log('🚀 ~ PublicService ~ createIPFS ~ response:', response)

      // WORKING
      const result = await this.pinata.upload.stream(createReadStream('./file.png'))
      console.log('🚀 ~ PublicService ~ uploadToIPFS ~ result:', result)
    } catch (error) {
      console.log('🚀 ~ PublicService ~ uploadToIPFS ~ error:', error)
    }
  }
}
```

Do your guys have any idea in here ?

Thank any solution

**Comment by climba03003** [comment]
If there is error, you should post the error message and stack.
From your given information, we doesn't knows what you means by working or not working.

**Comment by truongly1997** [comment]
Hi @climba03003 ,

I found the issue come from when I setting
`attachFieldsToBody: true`.

The file get from req.body to sending IPFS is loading forever.

After get file from req.file(). It working well as my expected
