### ISSUE TITLE
Parameter addToBody treats all requests as multipart

### ISSUE THREAD

**Issue by SkeLLLa** [fastify/fastify-multipart#62]
Hi. Here's small example:

```js
const fastify = require('fastify')();
const multipart = require('fastify-multipart');
const fs = require('fs');

fastify.register(multipart, {addToBody: true, sharedSchemaId: 'genericFile'});

fastify.get('/', async (req, rep) => {
  const stream = fs.createReadStream('index.html', 'utf8');
  rep.send(stream);
});

fastify.post('/upload', async (req, rep) => {
  // do something with file
});

(async () => {
  try {
    await fastify.ready();
    await fastify.listen(80);
  } catch (ex) {
    console.error(ex);
  }
})();
```

In this case it will handle all requests as multipart and will try to parse it. And if request is not multipart it will throw an exception.

Is that expected behaviour? I think it would be better if it will call that only for multipart requests. So the code in https://github.com/fastify/fastify-multipart/blob/master/index.js#L16 should look like this:
```
if (!req[kMultipart]) {
    next()
    return;
}
```
@Eomm you're probably should know about this.

**Comment by Eomm** [comment]
> Is that expected behaviour?

Nope! This needs a fix very soon, let me check

Thank you for the issue as usual 💪
