### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by johntom** [fastify/fastify-multipart#71]
I've tried to upload file(s) from postman with fastify-multipart and fastify-multer but get 
{
    "statusCode": 415,
    "code": "FST_ERR_CTP_INVALID_MEDIA_TYPE",
    "error": "Unsupported Media Type",
    "message": "FST_ERR_CTP_INVALID_MEDIA_TYPE: Unsupported Media Type: application/x-www-form-urlencoded"
}
Any ideas how to fix?
Thks,
John

**Comment by jsumners** [comment]
Use the `multipart/form-data` content type.

**Comment by johntom** [comment]
Thanks, That did it!

**Comment by johntom** [comment]
Thanks
