### ISSUE TITLE
get key value from request

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify-multipart#85]
Hello, i have a question, where my data after incomming :)

```
                let formData = new formdata();
                formData.append("aaa", JSON.stringify( { aaaaaa: 'aaaaaaaaaa' } ) );
                formData.append("bbb", JSON.stringify( { bbbbb: 'bbbbbbbbbbb' } ) );

                axios.post('http://localhost:3000/load', formData, {
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'multipart/form-data'
                    }
                })
```

server
```
fastify.post('/load', async (request, reply) => {
   how get data??? my aaa and bbb
    reply.send( await load.init(request) )
});
```
Or this only for files transfer?

**Comment by mcollina** [comment]
It’s all documented in the readme. Look for the ‘field’ event and the addToBody option

**Comment by borodadada** [comment]
i use doc, but dont work, formdata not recive on server side

```
server option from doc

const options = {
    addToBody: true,
    sharedSchemaId: 'MultipartFileType',
    onFile: (fieldName, stream, filename, encoding, mimetype, body) => {
        stream.resume()
    }
}
fastify.register(require('fastify-multipart'), options)

fastify.post('/load', 
{
    schema: {
        type: 'object',
        properties: {
          encoding: { type: 'string' },
          filename: { type: 'string' },
          limit: { type: 'boolean' },
          mimetype: { type: 'string' }
        }
    }
}, 
async (request, reply) => {
    console.log(req.body)
    reply.send( await load.init(request) )
});

```

send formdata, i use npm pack https://www.npmjs.com/package/form-data

```
                var form = new FormData();
                form.append('my_field', 'my value');
                form.append('my_buffer', new Buffer(10));

                axios.post('http://localhost:3000/load', form, {
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'multipart/form-data'
                    }
                })
                .then(function (response) {
                    console.log(response);
                })
                .catch(function (error) {
                    console.log(error);
                });
```

result 

```
    data: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'Multipart: Boundary not found'
    }
```

why it happens?

**Comment by Eomm** [comment]
Your error is the same explained here:
https://github.com/fastify/fastify-multipart/issues/82#issuecomment-515683212

You need to fix your requests header 👍🏼

**Comment by borodadada** [comment]
Okey, set 

```
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'multipart/form-data;boundary="boundary"'
                    }
```

on server side body = {}  empty

in options body on  addToBody: true

**Comment by borodadada** [comment]
mr. admin why you close theme, problem is real

**Comment by mcollina** [comment]
There are plenty of examples in https://github.com/fastify/fastify-multipart/blob/master/test/multipart.test.js.

**Comment by Douglasgomestosta** [comment]
it's too easy to upload files and fields with expressjs... why is too problematic to upload files and fields in fastifly? when the browser set the content-type, the file is sent but the field data don't work, and if i set the content-type "multipart/form-data;boundary="boundary"" the req.file(); shows undefined

**Comment by Uzlopak** [comment]
Because you need to make an informed decision regarding the file upload with fastifyjs. E.g. in expressjs you have the problem that you  load everything into the memory. This works out of the box and is maybe ok for beginners. But for production this could mean to expose a security risk. Imagine you run your http server in docker and you measure and set the used memory to 500 MB. You set in your expressjs server the maximum file size to 20 mb. So what I do is to upload 25 files with 20 MB at the same time, and voilá, docker will convict the container due to OOM. 

This is the classical scenario. And why? Because the implementer thought, that the default settings are battle proven. But it is not.

**Comment by Douglasgomestosta** [comment]
when i make a request with a file and a non-file field with fetch in google chrome(work on expressjs) the server show only the file, but when i make the request with the same file and a non-file field, the server show the two fields.... the fetcth request on chrome is the same that i use with expresjs
![Captura de tela 2024-01-13 165813](https://github.com/fastify/fastify-multipart/assets/11670854/7e171113-ed2d-429e-862f-463f9a8df9ce)

**Comment by Uzlopak** [comment]
I have no clue. Open a new Issue.
