### ISSUE TITLE
Can not get file data at some special scene

### ISSUE THREAD

**Issue by xland** [fastify/fastify-multipart#94]
My requirements:
- My client post 'multipart/form-data' type of data.
- I want to use schema to validate the client's data.
- I don't want to load the file's data into the memory.
- I want to specify the uploaded file's name.
- I register 'fastify-multipart' and handle post request in different js files.

My client code of post data:
```js
let imgFd = new FormData();
imgFd.append("token", '******');
imgFd.append("answerImg", file);
let xhr = new XMLHttpRequest();
xhr.open("POST", url, true);
xhr.withCredentials = true;
xhr.onreadystatechange = () => {
        if (xhr.readyState == 4 && (xhr.status == 200 || xhr.status == 304)) {
           console.log(xhr.responseText)
        }
    }
xhr.send(imgFd);
```
My server code of register fastify-multipart
```js
fastify.register(require('fastify-multipart'), {
            addToBody: true,
            sharedSchemaId: 'uploadFile',
            onFile: (fieldName, stream, filename, encoding, mimetype, body) => {
                stream.resume(); //???
            },
            limits: { fileSize: 1024 * 1024 * 8 },
        });
```
My server code of schema
```js
{
        body: {
            type: 'object',
            properties: {
                token: { type: 'string', minLength: 6, maxLength: 86 },
                answerImg: { type: 'array', items: 'uploadFile#' }
            },
            additionalProperties: false,
            required: ['token', 'answerImg']
        }
}
```
My server code of handler
```js
fastify.post('/abc', { schema: schemaAbove }, async(request, reply) => {
    let fullFileName = '';
    function handler(field, file, filename, encoding, mimetype) {
        let extname = path.extname(filename);
        fullFileName = `./uploads/${uuid()}_${id}${extname}`
        pump(file, fs.createWriteStream(fullFileName))
    }
    request.multipart(handler, function(err) {
        if (err) throw err;
        reply.send({ url: `http://127.0.0.1:3000${fullFileName.substr(1)}` });
    });
});
```

**Comment by Eomm** [comment]
> My client post 'multipart/form-data' type of data.

This plugin is the right choice 👍

> I want to use schema to validate the client's data.

Your schema seems ok

> I don't want to load the file's data into the memory.

If you set `addToBody: true` and you don't manage in the `onFile` you can't archive it.
Checkout in the readme the section `The onFile option define how the file streams are managed: ...`
Based on how you manage the streams, the memory will be used as well.

> I want to specify the uploaded file's name.

I don't understand: in the server, you have a stream and you can store it where you want in the server. You can't control the file's name since the files are in the users' devices

> I register 'fastify-multipart' and handle post request in different js files.

You can do it, but your `handler` is in conflict with the configuration:
if you use `addToBody: true` your `handler` function should be the `onFile`.
I suggest you start from [this example](https://github.com/fastify/fastify-multipart/blob/master/exampleValidation.js)

**Comment by xland** [comment]
@Eomm 
Thanks for your reply.
I have some questions about that example.（explain my requirements）

-  It loads the file's data into the memory,because it doesn't set the `onFile` option.
-  If I pass the  `onFile`  option to the `fastify.register` function, I cann't set the file's name easily.
(File name is from controller's logic code).
- If I pass per-request options to the `req.multipart` function,I must pass the `addToBody` option too.
If I do that I cann't use the schema to validate the client's data.
- I try to pass the  `addToBody`  option to the `fastify.register` function and the `onFile`  option to the `req.multipart` function.   Failed.  It seems the `fastify.register` priority levels is higher than the `req.multipart`.

**Comment by Eomm** [comment]
> It loads the file's data into the memory,because it doesn't set the onFile option.

Yes

> If I pass the onFile option to the fastify.register function, I cann't set the file's name easily.
(File name is from controller's logic code).

Yes, I understand. Maybe you could register the plugin in the controller

> If I pass per-request options to the req.multipart function,I must pass the addToBody option too.

Nope, if you use the per-request option the `addToBody` is not mandatory

> If I do that I cann't use the schema to validate the client's data.

True, the `addToBody` is mandatory to apply validation. This is not avoidable since if we don't read the file stream we can't compose the body. If we don't compose the body we can't validate it

> I try to pass the addToBody option to the fastify.register function and the onFile option to the req.multipart function. Failed. It seems the fastify.register priority levels is higher than the req.multipart.

True, the `addToBody` option will manage the streams, so you can't consume them with `req.multipart` since they are already gone. That param is a utility to write less code and "forget" about streams.
Maybe could you open a PR to write it better in the docs?

**Comment by xland** [comment]
Yes. I'm glad to help to improve the document.
But, What shold I do now?

I have an idea:

```js
//controllers.js
fastify.post('/abc', { schema }, async(request, reply) => {
    myGlobalObj.onFileHandler = (fieldName, stream, filename, encoding, mimetype, body) => {
        pump(stream, fs.createWriteStream('abc.rar'))
    }
    return { data: 'ok' };
})
```
```js
//plugins.js
fastify.register(require('fastify-multipart'), {
    addToBody: true,
    sharedSchemaId: 'uploadFile',
    onFile: (fieldName, stream, filename, encoding, mimetype, body) => {
        myGlobalObj.onFileHandler(fieldName, stream, filename, encoding, mimetype)
    },
    limits: { fileSize: 1024 * 1024 * 8 },
});
```
The code above is ugly.
But it can 

- Validate the form data 
- No need to load the file's data into the memory
- Set the file's name by logic code

Isn't it?

So, Should the plugin do these things for me?

**Comment by xland** [comment]
It seems wrong.

onFile event will fire before myGlobalObj.onFileHandler been setted

**Comment by Eomm** [comment]
This should works:

```
//controllers.js
myGlobalObj.onFileHandler = (fieldName, stream, filename, encoding, mimetype, body) => {
    pump(stream, fs.createWriteStream('abc.rar'))
}

fastify.post('/abc', { schema }, async(request, reply) => {
    return { data: 'ok' };
})

//plugins.js
fastify.register(require('fastify-multipart'), {
    addToBody: true,
    sharedSchemaId: 'uploadFile',
    onFile: myGlobalObj.onFileHandler,
    limits: { fileSize: 1024 * 1024 * 8 },
});
```

**Comment by xland** [comment]
@Eomm 
The file name `abc.rar` should come from the `fastify.post('/xyz'` controller
Can it be done?

**Comment by Eomm** [comment]
Which field? Because you can't access the body in that phase. The headers are ok instead

**Comment by xland** [comment]
I see.
Thanks.
I thought it is not a true issue.
So just close it.
